// Auto-generated by generate_widget_types.mjs — do not edit manually.
// This file contains all widget type definitions for runtime schema assembly.
// Each type is delimited by "// --- TypeName ---" for machine parsing.
export {};

// --- TimeseriesWidgetDefinition ---
interface TimeseriesWidgetDefinition {
  type: TimeseriesWidgetDefinitionType;
  /** List of timeseries widget requests. e.g. [ { "q/apm_query/log_query": "<METRIC_1>{<SCOPE_1>}" } ] */
  requests: (TimeseriesWidgetRequest | TimeseriesLocalDatasetRequest)[];
  yaxis?: WidgetAxis;
  right_yaxis?: WidgetAxis;
  markers?: WidgetMarker[];
  custom_links?: WidgetCustomLink[];
  title?: string;
  /** (screenboard only) Show the legend for this widget. */
  show_legend?: boolean;
  legend_size?: WidgetLegendSize;
  legend_layout?: TimeseriesWidgetLegendLayout;
  /** Columns displayed in the legend. */
  legend_columns?: TimeseriesWidgetLegendColumn[];
  title_size?: string;
  title_align?: WidgetTextAlign;
  description?: string;
  time?: WidgetTime;
}
// --- TimeseriesWidgetDefinitionType ---
type TimeseriesWidgetDefinitionType = "timeseries";
// --- TimeseriesWidgetRequest ---
interface TimeseriesWidgetRequest {
  queries?: FormulaAndFunctionQueryDefinition[];
  formulas?: WidgetFormula[];
  response_format?: FormulaAndFunctionResponseFormat;
  style?: TimeseriesRequestStyle;
  /** Used to define expression aliases. */
  metadata?: TimeseriesWidgetExpressionAlias[];
  display_type?: WidgetDisplayType;
  /** Whether to display a second y-axis on the right. */
  on_right_yaxis?: boolean;
}
// --- WidgetAxis ---
interface WidgetAxis {
  /** Possible values: `linear`, `log`, `sqrt`, `pow##` (e.g. `pow2`, `pow0.5`). @default linear */
  scale: string;
  /** @default auto */
  min: string;
  /** @default auto */
  max: string;
  include_zero?: boolean;
  /** Only usable on Scatterplot Widgets. */
  label?: string;
}
// --- WidgetMarker ---
/** Markers allow you to add visual conditional formatting for your graphs. */
interface WidgetMarker {
  /** Can be a single value `y = 15` or a range `0 < y < 10`. For Distribution widgets with `display_type` set to `percentile`, this should be a numeric percentile value (e.g. "90" for P90). e.g. y = 15 */
  value: string;
  /** Combination of: a severity (error, warning, ok, info) and a line type (dashed, solid, bold). For Distribution widgets, can be `percentile`. e.g. error dashed */
  display_type?: string;
  /** Label to display over the marker. e.g. Error threshold */
  label?: string;
  /** Timestamp for the widget. */
  time?: string;
}
// --- WidgetCustomLink ---
interface WidgetCustomLink {
  /** Keep the label short and descriptive. Use metrics and tags as variables. e.g. Search logs for {{host}} */
  label?: string;
  /** URL must include `http` or `https`. A relative URL must start with `/`. e.g. https://app.datadoghq.com/logs?query={{host}} */
  link?: string;
  /** The label ID that refers to a context menu link. Can be `logs`, `hosts`, `traces`, `profiles`, `processes`, `containers`, or `rum`. e.g. logs */
  override_label?: string;
  /** The flag for toggling context menu link visibility. */
  is_hidden?: boolean;
}
// --- WidgetLegendSize ---
/** Should be one of "0", "2", "4", "8", "16", or "auto". */
type WidgetLegendSize = string;
// --- TimeseriesWidgetLegendLayout ---
type TimeseriesWidgetLegendLayout = "auto" | "horizontal" | "vertical";
// --- TimeseriesWidgetLegendColumn ---
type TimeseriesWidgetLegendColumn = "value" | "avg" | "sum" | "min" | "max";
// --- WidgetTextAlign ---
type WidgetTextAlign = "center" | "left" | "right";
// --- WidgetTime ---
type WidgetTime = WidgetLegacyLiveSpan | WidgetNewLiveSpan | WidgetNewFixedSpan;
// --- FormulaAndFunctionQueryDefinition ---
type FormulaAndFunctionQueryDefinition = FormulaAndFunctionMetricQueryDefinition | FormulaAndFunctionEventQueryDefinition | FormulaAndFunctionProcessQueryDefinition | FormulaAndFunctionApmDependencyStatsQueryDefinition | FormulaAndFunctionApmMetricsQueryDefinition | FormulaAndFunctionSLOQueryDefinition | FormulaAndFunctionCloudCostQueryDefinition | FormulaAndFunctionProductAnalyticsExtendedQueryDefinition | FormulaAndFunctionUserJourneyQueryDefinition | FormulaAndFunctionRetentionQueryDefinition;
// --- WidgetFormula ---
interface WidgetFormula {
  /** String expression built from queries, formulas, and functions. e.g. func(a) + b */
  formula: string;
  limit?: WidgetFormulaLimit;
  conditional_formats?: WidgetConditionalFormat[];
  cell_display_mode?: TableWidgetCellDisplayMode;
  cell_display_mode_options?: WidgetFormulaCellDisplayModeOptions;
  number_format?: WidgetNumberFormat;
  style?: WidgetFormulaStyle;
  /** Expression alias. */
  alias?: string;
}
// --- FormulaAndFunctionResponseFormat ---
/** Timeseries, scalar, or event list response. Event list response formats are supported by Geomap widgets. */
type FormulaAndFunctionResponseFormat = "timeseries" | "scalar" | "event_list";
// --- TimeseriesRequestStyle ---
interface TimeseriesRequestStyle {
  palette?: string;
  line_type?: WidgetLineType;
  line_width?: WidgetLineWidth;
  order_by?: WidgetStyleOrderBy;
  /** If true, the value is displayed as a label relative to the data point. */
  has_value_labels?: boolean;
}
// --- TimeseriesWidgetExpressionAlias ---
interface TimeseriesWidgetExpressionAlias {
  /** Expression name. */
  expression: string;
  /** Expression alias. */
  alias_name?: string;
}
// --- WidgetDisplayType ---
type WidgetDisplayType = "area" | "bars" | "line" | "overlay";
// --- WidgetLegacyLiveSpan ---
interface WidgetLegacyLiveSpan {
  live_span?: WidgetLiveSpan;
  /** Whether to hide incomplete cost data in the widget. */
  hide_incomplete_cost_data?: boolean;
}
// --- WidgetNewLiveSpan ---
/** Used for arbitrary live span times, such as 17 minutes or 6 hours. */
interface WidgetNewLiveSpan {
  type: WidgetNewLiveSpanType;
  /** e.g. 4 */
  value: number;
  unit: WidgetLiveSpanUnit;
  /** Whether to hide incomplete cost data in the widget. */
  hide_incomplete_cost_data?: boolean;
}
// --- WidgetNewFixedSpan ---
/** Used for fixed span times, such as 'March 1 to March 7'. */
interface WidgetNewFixedSpan {
  type: WidgetNewFixedSpanType;
  /** Start time in milliseconds since epoch. e.g. 1712080128000 */
  from: number;
  /** End time in milliseconds since epoch. e.g. 1712083128000 */
  to: number;
  /** Whether to hide incomplete cost data in the widget. */
  hide_incomplete_cost_data?: boolean;
}
// --- FormulaAndFunctionMetricQueryDefinition ---
interface FormulaAndFunctionMetricQueryDefinition {
  data_source: FormulaAndFunctionMetricDataSource;
  /** e.g. avg:system.cpu.user{*} */
  query: string;
  aggregator?: FormulaAndFunctionMetricAggregation;
  /** Name of the query for use in formulas. e.g. my_query */
  name: string;
  cross_org_uuids?: CrossOrgUuids;
  semantic_mode?: FormulaAndFunctionMetricSemanticMode;
}
// --- FormulaAndFunctionEventQueryDefinition ---
interface FormulaAndFunctionEventQueryDefinition {
  data_source: FormulaAndFunctionEventsDataSource;
  search?: FormulaAndFunctionEventQueryDefinitionSearch;
  /** An array of index names to query in the stream. Omit or use `[]` to query all indexes at once. e.g. [ "days-3", "days-7" ] */
  indexes?: string[];
  compute: FormulaAndFunctionEventQueryDefinitionCompute;
  group_by?: FormulaAndFunctionEventQueryGroupByConfig;
  /** Name of the query for use in formulas. e.g. query_errors */
  name: string;
  /** Option for storage location. e.g. indexes */
  storage?: string;
  cross_org_uuids?: CrossOrgUuids;
}
// --- FormulaAndFunctionProcessQueryDefinition ---
interface FormulaAndFunctionProcessQueryDefinition {
  data_source: FormulaAndFunctionProcessQueryDataSource;
  /** e.g. avg:system.cpu.user{*} */
  metric: string;
  /** Text to use as filter. */
  text_filter?: string;
  tag_filters?: string[];
  /** Number of hits to return. */
  limit?: number;
  sort?: QuerySortOrder;
  aggregator?: FormulaAndFunctionMetricAggregation;
  is_normalized_cpu?: boolean;
  /** Name of query for use in formulas. e.g. query_errors */
  name: string;
  cross_org_uuids?: CrossOrgUuids;
}
// --- FormulaAndFunctionApmDependencyStatsQueryDefinition ---
interface FormulaAndFunctionApmDependencyStatsQueryDefinition {
  data_source: FormulaAndFunctionApmDependencyStatsDataSource;
  /** APM environment. e.g. staging */
  env: string;
  stat: FormulaAndFunctionApmDependencyStatName;
  /** Name of operation on service. e.g. cassandra.query */
  operation_name: string;
  /** APM resource. e.g. DELETE FROM foo WHERE baz = ? */
  resource_name: string;
  /** APM service. e.g. cassandra */
  service: string;
  /** The name of the second primary tag used within APM; required when `primary_tag_value` is specified. See https://docs.datadoghq.com/tracing/guide/setting_primary_tags_to_scope/#add-a-second-primary-tag-in-datadog. e.g. datacenter */
  primary_tag_name?: string;
  /** Filter APM data by the second primary tag. `primary_tag_name` must also be specified. e.g. staging */
  primary_tag_value?: string;
  /** Determines whether stats for upstream or downstream dependencies should be queried. */
  is_upstream?: boolean;
  /** Name of query for use in formulas. e.g. query_errors */
  name: string;
  cross_org_uuids?: CrossOrgUuids;
}
// --- FormulaAndFunctionApmMetricsQueryDefinition ---
interface FormulaAndFunctionApmMetricsQueryDefinition {
  data_source: FormulaAndFunctionApmMetricsDataSource;
  /** Name of this query for use in formulas. e.g. query_errors */
  name: string;
  stat: FormulaAndFunctionApmMetricStatName;
  /** APM service name. e.g. web-store */
  service?: string;
  /** Tags to query for a specific downstream entity (peer.service, peer.db_instance, peer.s3, peer.s3.bucket, etc.). */
  peer_tags?: string[];
  /** The hash of a specific resource to filter by. e.g. abc123 */
  resource_hash?: string;
  /** The full name of a specific resource to filter by. e.g. GET /api/v1/users */
  resource_name?: string;
  /** Name of operation on service. If not provided, the primary operation name is used. e.g. web.request */
  operation_name?: string;
  /** Optional operation mode to aggregate across operation names. e.g. primary */
  operation_mode?: string;
  /** Additional filters using metrics query syntax (e.g., env, primary_tag). e.g. env:prod */
  query_filter?: string;
  group_by?: string[];
  span_kind?: FormulaAndFunctionApmMetricsSpanKind;
}
// --- FormulaAndFunctionSLOQueryDefinition ---
interface FormulaAndFunctionSLOQueryDefinition {
  data_source: FormulaAndFunctionSLODataSource;
  /** ID of an SLO to query measures. e.g. 12345678910 */
  slo_id: string;
  measure: FormulaAndFunctionSLOMeasure;
  group_mode?: FormulaAndFunctionSLOGroupMode;
  slo_query_type?: FormulaAndFunctionSLOQueryType;
  /** Name of the query for use in formulas. e.g. my_slo */
  name?: string;
  /** Additional filters applied to the SLO query. e.g. host:host_a,env:prod */
  additional_query_filters?: string;
  cross_org_uuids?: CrossOrgUuids;
}
// --- FormulaAndFunctionCloudCostQueryDefinition ---
interface FormulaAndFunctionCloudCostQueryDefinition {
  data_source: FormulaAndFunctionCloudCostDataSource;
  /** e.g. sum:aws.cost.amortized{*} */
  query: string;
  aggregator?: WidgetAggregator;
  /** Name of the query for use in formulas. e.g. my_query */
  name: string;
  cross_org_uuids?: CrossOrgUuids;
}
// --- FormulaAndFunctionProductAnalyticsExtendedQueryDefinition ---
interface FormulaAndFunctionProductAnalyticsExtendedQueryDefinition {
  data_source: FormulaAndFunctionProductAnalyticsExtendedDataSource;
  /** Name of the query for use in formulas. e.g. query1 */
  name: string;
  query: ProductAnalyticsBaseQuery;
  compute: ProductAnalyticsExtendedCompute;
  group_by?: ProductAnalyticsExtendedGroupBy[];
  audience_filters?: ProductAnalyticsAudienceFilters;
  /** e.g. [ "*" ] */
  indexes?: FormulaAndFunctionProductAnalyticsExtendedQueryDefinitionIndexesItems[];
}
// --- FormulaAndFunctionUserJourneyQueryDefinition ---
interface FormulaAndFunctionUserJourneyQueryDefinition {
  data_source: ProductAnalyticsFunnelDataSource;
  /** Name of the query for use in formulas. e.g. query1 */
  name: string;
  search: UserJourneySearch;
  compute: UserJourneyFormulaCompute;
  group_by?: UserJourneyFormulaGroupBy[];
}
// --- FormulaAndFunctionRetentionQueryDefinition ---
interface FormulaAndFunctionRetentionQueryDefinition {
  data_source: RetentionDataSource;
  /** Name of the query for use in formulas. e.g. query1 */
  name: string;
  search: RetentionSearch;
  compute: RetentionCompute;
  group_by?: RetentionGroupBy[];
}
// --- WidgetFormulaLimit ---
interface WidgetFormulaLimit {
  /** Number of results to return. */
  count?: number;
  order?: QuerySortOrder;
}
// --- WidgetConditionalFormat ---
interface WidgetConditionalFormat {
  comparator: WidgetComparator;
  /** Value for the comparator. */
  value: number;
  palette: WidgetPalette;
  /** Color palette to apply to the background, same values available as palette. */
  custom_bg_color?: string;
  /** Color palette to apply to the foreground, same values available as palette. */
  custom_fg_color?: string;
  /** Displays an image as the background. */
  image_url?: string;
  hide_value?: boolean;
  /** Defines the displayed timeframe. */
  timeframe?: string;
  /** Metric from the request to correlate this conditional format with. */
  metric?: string;
}
// --- TableWidgetCellDisplayMode ---
type TableWidgetCellDisplayMode = "number" | "bar" | "trend";
// --- WidgetFormulaCellDisplayModeOptions ---
/** Only applicable if `cell_display_mode` is set to `trend`. */
interface WidgetFormulaCellDisplayModeOptions {
  trend_type?: WidgetFormulaCellDisplayModeOptionsTrendType;
  y_scale?: WidgetFormulaCellDisplayModeOptionsYScale;
}
// --- WidgetNumberFormat ---
interface WidgetNumberFormat {
  unit?: NumberFormatUnit;
  unit_scale?: NumberFormatUnitScale;
}
// --- WidgetFormulaStyle ---
interface WidgetFormulaStyle {
  /** The color palette used to display the formula. A guide to the available color palettes can be found at https://docs.datadoghq.com/dashboards/guide/widget_colors */
  palette?: string;
  /** Index specifying which color to use within the palette. */
  palette_index?: number;
}
// --- WidgetLineType ---
type WidgetLineType = "dashed" | "dotted" | "solid";
// --- WidgetLineWidth ---
type WidgetLineWidth = "normal" | "thick" | "thin";
// --- WidgetStyleOrderBy ---
/** - `tags`: Order series alphabetically by tag name (default behavior) - `values`: Order series by their current metric values (typically descending) */
type WidgetStyleOrderBy = "tags" | "values";
// --- WidgetLiveSpan ---
type WidgetLiveSpan = "1m" | "5m" | "10m" | "15m" | "30m" | "1h" | "4h" | "1d" | "2d" | "1w" | "1mo" | "3mo" | "6mo" | "week_to_date" | "month_to_date" | "1y" | "alert";
// --- WidgetNewLiveSpanType ---
type WidgetNewLiveSpanType = "live";
// --- WidgetLiveSpanUnit ---
type WidgetLiveSpanUnit = "minute" | "hour" | "day" | "week" | "month" | "year";
// --- WidgetNewFixedSpanType ---
type WidgetNewFixedSpanType = "fixed";
// --- FormulaAndFunctionMetricDataSource ---
type FormulaAndFunctionMetricDataSource = "metrics";
// --- FormulaAndFunctionMetricAggregation ---
type FormulaAndFunctionMetricAggregation = "avg" | "min" | "max" | "sum" | "last" | "area" | "l2norm" | "percentile";
// --- CrossOrgUuids ---
/** The source organization UUID for cross organization queries. e.g. [ "6434abde-xxxx-yyyy-zzzz-da7ad0900001" ] */
type CrossOrgUuids = string[];
// --- FormulaAndFunctionMetricSemanticMode ---
/** Determines how metrics from different sources are combined or displayed. */
type FormulaAndFunctionMetricSemanticMode = "combined" | "native";
// --- FormulaAndFunctionEventsDataSource ---
type FormulaAndFunctionEventsDataSource = "logs" | "spans" | "network" | "rum" | "security_signals" | "profiles" | "audit" | "events" | "ci_tests" | "ci_pipelines" | "incident_analytics" | "product_analytics" | "on_call_events" | "errors" | "llm_observability";
// --- FormulaAndFunctionEventQueryDefinitionSearch ---
interface FormulaAndFunctionEventQueryDefinitionSearch {
  /** Events search string. e.g. service:query */
  query: string;
}
// --- FormulaAndFunctionEventQueryDefinitionCompute ---
interface FormulaAndFunctionEventQueryDefinitionCompute {
  aggregation: FormulaAndFunctionEventAggregation;
  /** A time interval in milliseconds. */
  interval?: number;
  /** Measurable attribute to compute. e.g. @duration */
  metric?: string;
}
// --- FormulaAndFunctionEventQueryGroupByConfig ---
/** Accepts either a list of facet objects or a flat object that specifies a list of facet fields. */
type FormulaAndFunctionEventQueryGroupByConfig = FormulaAndFunctionEventQueryGroupByList | FormulaAndFunctionEventQueryGroupByFields;
// --- FormulaAndFunctionProcessQueryDataSource ---
type FormulaAndFunctionProcessQueryDataSource = "process" | "container";
// --- QuerySortOrder ---
/** @default desc */
type QuerySortOrder = "asc" | "desc";
// --- FormulaAndFunctionApmDependencyStatsDataSource ---
type FormulaAndFunctionApmDependencyStatsDataSource = "apm_dependency_stats";
// --- FormulaAndFunctionApmDependencyStatName ---
type FormulaAndFunctionApmDependencyStatName = "avg_duration" | "avg_root_duration" | "avg_spans_per_trace" | "error_rate" | "pct_exec_time" | "pct_of_traces" | "total_traces_count";
// --- FormulaAndFunctionApmMetricsDataSource ---
type FormulaAndFunctionApmMetricsDataSource = "apm_metrics";
// --- FormulaAndFunctionApmMetricStatName ---
type FormulaAndFunctionApmMetricStatName = "errors" | "error_rate" | "errors_per_second" | "latency_avg" | "latency_max" | "latency_p50" | "latency_p75" | "latency_p90" | "latency_p95" | "latency_p99" | "latency_p999" | "latency_distribution" | "hits" | "hits_per_second" | "total_time" | "apdex";
// --- FormulaAndFunctionApmMetricsSpanKind ---
/** Describes the relationship between the span, its parents, and its children in a trace. */
type FormulaAndFunctionApmMetricsSpanKind = "consumer" | "server" | "client" | "producer" | "internal";
// --- FormulaAndFunctionSLODataSource ---
type FormulaAndFunctionSLODataSource = "slo";
// --- FormulaAndFunctionSLOMeasure ---
type FormulaAndFunctionSLOMeasure = "good_events" | "bad_events" | "good_minutes" | "bad_minutes" | "slo_status" | "error_budget_remaining" | "burn_rate" | "error_budget_burndown";
// --- FormulaAndFunctionSLOGroupMode ---
type FormulaAndFunctionSLOGroupMode = "overall" | "components";
// --- FormulaAndFunctionSLOQueryType ---
type FormulaAndFunctionSLOQueryType = "metric" | "monitor" | "time_slice";
// --- FormulaAndFunctionCloudCostDataSource ---
type FormulaAndFunctionCloudCostDataSource = "cloud_cost";
// --- WidgetAggregator ---
type WidgetAggregator = "avg" | "last" | "max" | "min" | "sum" | "percentile";
// --- FormulaAndFunctionProductAnalyticsExtendedDataSource ---
type FormulaAndFunctionProductAnalyticsExtendedDataSource = "product_analytics_extended";
// --- ProductAnalyticsBaseQuery ---
type ProductAnalyticsBaseQuery = ProductAnalyticsEventQuery;
// --- ProductAnalyticsExtendedCompute ---
interface ProductAnalyticsExtendedCompute {
  aggregation: FormulaAndFunctionEventAggregation;
  /** Measurable attribute to compute. e.g. @usr.id */
  metric?: string;
  /** Name of the compute for use in formulas. e.g. query1 */
  name?: string;
  /** Fixed-width time bucket interval in milliseconds. Mutually exclusive with `rollup`. e.g. 60000 */
  interval?: number;
  /** Calendar-aligned time bucket for time series queries. Mutually exclusive with `interval`. */
  rollup?: CalendarInterval;
}
// --- ProductAnalyticsExtendedGroupBy ---
interface ProductAnalyticsExtendedGroupBy {
  /** Facet name to group by. e.g. @geo.country */
  facet: string;
  /** Maximum number of groups to return. e.g. 10 */
  limit?: number;
  sort?: FormulaAndFunctionEventQueryGroupBySort;
  /** Whether to exclude events missing the group-by facet. */
  should_exclude_missing?: boolean;
}
// --- ProductAnalyticsAudienceFilters ---
interface ProductAnalyticsAudienceFilters {
  users?: ProductAnalyticsAudienceUserSubquery[];
  segments?: ProductAnalyticsAudienceSegmentSubquery[];
  accounts?: ProductAnalyticsAudienceAccountSubquery[];
  /** An optional filter condition applied to the audience subquery. */
  filter_condition?: string;
}
// --- FormulaAndFunctionProductAnalyticsExtendedQueryDefinitionIndexesItems ---
/** Use `"*"` to query all indexes. */
type FormulaAndFunctionProductAnalyticsExtendedQueryDefinitionIndexesItems = "*";
// --- ProductAnalyticsFunnelDataSource ---
type ProductAnalyticsFunnelDataSource = "product_analytics_journey";
// --- UserJourneySearch ---
interface UserJourneySearch {
  /** Node objects mapping. */
  node_objects: {
  [key: string]: ProductAnalyticsBaseQuery;
  };
  /** Expression string. e.g. node_0 -> node_1 */
  expression: string;
  /** Step aliases mapping. */
  step_aliases?: {
  [key: string]: string;
  };
  join_keys?: UserJourneyJoinKeys;
  filters?: UserJourneySearchFilters;
}
// --- UserJourneyFormulaCompute ---
interface UserJourneyFormulaCompute {
  aggregation: FormulaAndFunctionEventAggregation;
  metric?: UserJourneyFormulaComputeMetric;
  /** Time bucket interval in milliseconds. e.g. 60000 */
  interval?: number;
  target?: UserJourneySearchTarget;
}
// --- UserJourneyFormulaGroupBy ---
interface UserJourneyFormulaGroupBy {
  /** Facet name to group by. e.g. @usr.email */
  facet: string;
  /** Maximum number of groups to return. e.g. 10 */
  limit?: number;
  sort?: FormulaAndFunctionEventQueryGroupBySort;
  /** Whether to exclude events missing the group-by facet. */
  should_exclude_missing?: boolean;
  target?: UserJourneySearchTarget;
}
// --- RetentionDataSource ---
type RetentionDataSource = "product_analytics_retention";
// --- RetentionSearch ---
interface RetentionSearch {
  cohort_criteria: RetentionCohortCriteria;
  retention_entity: RetentionEntity;
  return_condition: RetentionReturnCondition;
  return_criteria?: RetentionReturnCriteria;
  filters?: RetentionFilters;
}
// --- RetentionCompute ---
interface RetentionCompute {
  aggregation: EventsAggregation;
  metric: RetentionComputeMetric;
}
// --- RetentionGroupBy ---
interface RetentionGroupBy {
  /** Facet to group by. e.g. @geo.country */
  facet: string;
  should_exclude_missing?: boolean;
  sort?: RetentionGroupBySort;
  /** Maximum number of groups. e.g. 10 */
  limit?: number;
  target: RetentionGroupByTarget;
  /** Source field. e.g. @geo.country */
  source?: string;
}
// --- WidgetComparator ---
type WidgetComparator = "=" | ">" | ">=" | "<" | "<=";
// --- WidgetPalette ---
type WidgetPalette = "blue" | "custom_bg" | "custom_image" | "custom_text" | "gray_on_white" | "grey" | "green" | "orange" | "red" | "red_on_white" | "white_on_gray" | "white_on_green" | "green_on_white" | "white_on_red" | "white_on_yellow" | "yellow_on_white" | "black_on_light_yellow" | "black_on_light_green" | "black_on_light_red";
// --- WidgetFormulaCellDisplayModeOptionsTrendType ---
type WidgetFormulaCellDisplayModeOptionsTrendType = "area" | "line" | "bars";
// --- WidgetFormulaCellDisplayModeOptionsYScale ---
type WidgetFormulaCellDisplayModeOptionsYScale = "shared" | "independent";
// --- NumberFormatUnit ---
type NumberFormatUnit = NumberFormatUnitCanonical | NumberFormatUnitCustom;
// --- NumberFormatUnitScale ---
type NumberFormatUnitScale = {
  type?: NumberFormatUnitScaleType;
  /** e.g. bytes */
  unit_name?: string;
  } | null;
// --- FormulaAndFunctionEventAggregation ---
type FormulaAndFunctionEventAggregation = "count" | "cardinality" | "median" | "pc75" | "pc90" | "pc95" | "pc98" | "pc99" | "sum" | "min" | "max" | "avg";
// --- FormulaAndFunctionEventQueryGroupByList ---
type FormulaAndFunctionEventQueryGroupByList = FormulaAndFunctionEventQueryGroupBy[];
// --- FormulaAndFunctionEventQueryGroupByFields ---
/** Flat group by configuration using multiple event facet fields. */
interface FormulaAndFunctionEventQueryGroupByFields {
  /** List of event facets to group by. e.g. [ "hostname", "service" ] */
  fields: string[];
  sort?: FormulaAndFunctionEventQueryGroupBySort;
  /** Number of groups to return. e.g. 10 */
  limit?: number;
}
// --- ProductAnalyticsEventQuery ---
interface ProductAnalyticsEventQuery {
  data_source: ProductAnalyticsEventDataSource;
  search: ProductAnalyticsEventQuerySearch;
}
// --- CalendarInterval ---
interface CalendarInterval {
  type: CalendarIntervalType;
  /** Alignment of the interval. For `day`, use hours (e.g. `1am`, `14`). For `week`, use day names (e.g. `monday`). For `month`, use day-of-month ordinals (e.g. `1st`, `15th`). For `year` or `quarter`, use month names (e.g. `january`). */
  alignment?: string;
  /** Timezone for the interval. e.g. UTC */
  timezone?: string;
  /** Quantity of the interval. e.g. 1 */
  quantity?: number;
}
// --- FormulaAndFunctionEventQueryGroupBySort ---
interface FormulaAndFunctionEventQueryGroupBySort {
  /** Metric used for sorting group by results. */
  metric?: string;
  aggregation: FormulaAndFunctionEventAggregation;
  order?: QuerySortOrder;
}
// --- ProductAnalyticsAudienceUserSubquery ---
interface ProductAnalyticsAudienceUserSubquery {
  name?: string;
  /** The query string for the user subquery. */
  query?: string;
}
// --- ProductAnalyticsAudienceSegmentSubquery ---
interface ProductAnalyticsAudienceSegmentSubquery {
  name?: string;
  /** The unique identifier of the segment. */
  segment_id?: string;
}
// --- ProductAnalyticsAudienceAccountSubquery ---
interface ProductAnalyticsAudienceAccountSubquery {
  name?: string;
  /** The query string for the account subquery. */
  query?: string;
}
// --- UserJourneyJoinKeys ---
interface UserJourneyJoinKeys {
  /** Primary join key. e.g. @session.id */
  primary: string;
  secondary?: string[];
}
// --- UserJourneySearchFilters ---
interface UserJourneySearchFilters {
  /** e.g. @session.type:user */
  string_filter?: string;
  graph_filters?: UserJourneySearchGraphFilter[];
  audience_filters?: ProductAnalyticsAudienceFilters;
}
// --- UserJourneyFormulaComputeMetric ---
/** `__dd.conversion` and `__dd.conversion_rate` accept `count` and `cardinality` as aggregations. `__dd.time_to_convert` accepts `avg`, `median`, `pc75`, `pc95`, `pc98`, `pc99`, `min`, and `max`. */
type UserJourneyFormulaComputeMetric = "__dd.conversion" | "__dd.conversion_rate" | "__dd.time_to_convert";
// --- UserJourneySearchTarget ---
interface UserJourneySearchTarget {
  /** e.g. step */
  type: string;
  /** e.g. node_0 */
  start?: string;
  /** e.g. node_1 */
  end?: string;
  /** e.g. node_0 */
  value?: string;
}
// --- RetentionCohortCriteria ---
interface RetentionCohortCriteria {
  base_query: ProductAnalyticsBaseQuery;
  time_interval: RetentionCohortCriteriaTimeInterval;
}
// --- RetentionEntity ---
/** Entity to track for retention. */
type RetentionEntity = "@usr.id" | "@account.id";
// --- RetentionReturnCondition ---
type RetentionReturnCondition = "conversion_on" | "conversion_on_or_after";
// --- RetentionReturnCriteria ---
interface RetentionReturnCriteria {
  base_query: ProductAnalyticsBaseQuery;
  time_interval?: RetentionReturnCriteriaTimeInterval;
}
// --- RetentionFilters ---
interface RetentionFilters {
  /** e.g. @session.type:user */
  string_filter?: string;
  audience_filters?: ProductAnalyticsAudienceFilters;
}
// --- EventsAggregation ---
type EventsAggregation = EventsAggregationValue | EventsAggregationPercentile;
// --- RetentionComputeMetric ---
type RetentionComputeMetric = "__dd.retention" | "__dd.retention_rate";
// --- RetentionGroupBySort ---
interface RetentionGroupBySort {
  order?: WidgetSort;
}
// --- RetentionGroupByTarget ---
type RetentionGroupByTarget = "cohort" | "return_period";
// --- NumberFormatUnitCanonical ---
interface NumberFormatUnitCanonical {
  type?: NumberFormatUnitScaleType;
  /** e.g. bytes */
  unit_name?: string;
  /** The name of the unit per item. e.g. bytes */
  per_unit_name?: string;
}
// --- NumberFormatUnitCustom ---
interface NumberFormatUnitCustom {
  type?: NumberFormatUnitCustomType;
  /** The label for the custom unit. */
  label?: string;
}
// --- NumberFormatUnitScaleType ---
type NumberFormatUnitScaleType = "canonical_unit";
// --- FormulaAndFunctionEventQueryGroupBy ---
interface FormulaAndFunctionEventQueryGroupBy {
  /** Event facet. e.g. status. */
  facet: string;
  sort?: FormulaAndFunctionEventQueryGroupBySort;
  /** Number of groups to return. e.g. 10 */
  limit?: number;
}
// --- ProductAnalyticsEventDataSource ---
type ProductAnalyticsEventDataSource = "product_analytics";
// --- ProductAnalyticsEventQuerySearch ---
interface ProductAnalyticsEventQuerySearch {
  /** RUM event search query used to filter views or actions. e.g. @type:view @view.name:/home */
  query: string;
}
// --- CalendarIntervalType ---
type CalendarIntervalType = "day" | "week" | "month" | "year" | "quarter" | "minute" | "hour";
// --- UserJourneySearchGraphFilter ---
interface UserJourneySearchGraphFilter {
  /** e.g. count */
  name?: string;
  /** e.g. gt */
  operator?: string;
  value?: number;
  target?: UserJourneySearchTarget;
}
// --- RetentionCohortCriteriaTimeInterval ---
interface RetentionCohortCriteriaTimeInterval {
  type: RetentionCohortCriteriaTimeIntervalType;
  value: CalendarInterval;
}
// --- RetentionReturnCriteriaTimeInterval ---
interface RetentionReturnCriteriaTimeInterval {
  type: RetentionReturnCriteriaTimeIntervalType;
  value: number;
  unit: RetentionReturnCriteriaTimeIntervalUnit;
}
// --- EventsAggregationValue ---
type EventsAggregationValue = "avg" | "cardinality" | "count" | "delta" | "earliest" | "latest" | "max" | "median" | "min" | "most_frequent" | "sum";
// --- EventsAggregationPercentile ---
/** Percentile aggregation. */
type EventsAggregationPercentile = string;
// --- WidgetSort ---
type WidgetSort = "asc" | "desc";
// --- NumberFormatUnitCustomType ---
type NumberFormatUnitCustomType = "custom_unit_label";
// --- RetentionCohortCriteriaTimeIntervalType ---
type RetentionCohortCriteriaTimeIntervalType = "calendar";
// --- RetentionReturnCriteriaTimeIntervalType ---
type RetentionReturnCriteriaTimeIntervalType = "fixed";
// --- RetentionReturnCriteriaTimeIntervalUnit ---
type RetentionReturnCriteriaTimeIntervalUnit = "day" | "week" | "month";
// --- DistributionWidgetDefinition ---
interface DistributionWidgetDefinition {
  /** List of markers. e.g. [ { "display_type": "percentile", "value": "90" } ] */
  markers?: WidgetMarker[];
  type: DistributionWidgetDefinitionType;
  /** Array of one request object to display in the widget. See the dedicated [Request JSON schema documentation](https://docs.datadoghq.com/dashboards/graphing_json/request_json) to learn how to build the `REQUEST_SCHEMA`. */
  requests: DistributionWidgetRequest[];
  title?: string;
  title_size?: string;
  title_align?: WidgetTextAlign;
  description?: string;
  time?: WidgetTime;
  xaxis?: DistributionWidgetXAxis;
  yaxis?: DistributionWidgetYAxis;
  custom_links?: WidgetCustomLink[];
}
// --- DistributionWidgetDefinitionType ---
type DistributionWidgetDefinitionType = "distribution";
// --- DistributionWidgetRequest ---
interface DistributionWidgetRequest {
  apm_stats_query?: ApmStatsQueryDefinition;
  /** Distribution of point values for distribution metrics. Renders a histogram of raw metric data points. */
  request_type?: WidgetHistogramRequestType;
  query?: DistributionWidgetHistogramRequestQuery;
  /** Distribution of aggregated grouped queries. Use `request_type` instead for distribution of point values from distribution metrics. */
  response_format?: FormulaAndFunctionResponseFormat;
  queries?: FormulaAndFunctionQueryDefinition[];
  formulas?: WidgetFormula[];
  style?: WidgetStyle;
}
// --- DistributionWidgetXAxis ---
interface DistributionWidgetXAxis {
  /** Possible values are `linear`. @default linear */
  scale: string;
  /** Takes a number, percentile (p90 === 90th percentile), or auto. @default auto */
  min: string;
  /** Takes a number, percentile (p90 === 90th percentile), or auto. @default auto */
  max: string;
  include_zero?: boolean;
  /** Number of value buckets to target, also known as the resolution of the value bins. */
  num_buckets?: number;
}
// --- DistributionWidgetYAxis ---
interface DistributionWidgetYAxis {
  /** Possible values are `linear` or `log`. @default linear */
  scale: string;
  /** Takes a number, or auto. @default auto */
  min: string;
  /** Takes a number, or auto. @default auto */
  max: string;
  include_zero?: boolean;
  /** The label of the axis to display on the graph. */
  label?: string;
}
// --- ApmStatsQueryDefinition ---
/** The APM stats query for table and distributions widgets. */
interface ApmStatsQueryDefinition {
  /** Service name. e.g. web-store */
  service: string;
  /** Environment name. e.g. prod */
  env: string;
  /** Operation name associated with service. e.g. rack.request */
  name: string;
  /** The organization's host group name and value. e.g. datacenter:* */
  primary_tag: string;
  row_type: ApmStatsQueryRowType;
  /** Resource name. e.g. CartsController */
  resource?: string;
  /** Column properties used by the front end for display. */
  columns?: ApmStatsQueryColumnType[];
}
// --- WidgetHistogramRequestType ---
/** Query space aggregator must be `histogram:<metric name>` for points distributions. */
type WidgetHistogramRequestType = "histogram";
// --- DistributionWidgetHistogramRequestQuery ---
type DistributionWidgetHistogramRequestQuery = FormulaAndFunctionMetricQueryDefinition | FormulaAndFunctionEventQueryDefinition | FormulaAndFunctionApmMetricsQueryDefinition;
// --- WidgetStyle ---
interface WidgetStyle {
  palette?: string;
}
// --- ApmStatsQueryRowType ---
type ApmStatsQueryRowType = "service" | "resource" | "span";
// --- ApmStatsQueryColumnType ---
interface ApmStatsQueryColumnType {
  /** Column name. e.g. Reqs */
  name: string;
  /** A user-assigned alias for the column. e.g. Requests */
  alias?: string;
  order?: WidgetSort;
  cell_display_mode?: TableWidgetCellDisplayMode;
}
// --- GeomapWidgetDefinition ---
interface GeomapWidgetDefinition {
  type: GeomapWidgetDefinitionType;
  /** Array of request objects to display in the widget. May include an optional request for the region layer and/or an optional request for the points layer. Region layer requests must contain a `group-by` tag whose value is a country ISO code. See the [Request JSON schema documentation](https://docs.datadoghq.com/dashboards/graphing_json/request_json) for information about building the `REQUEST_SCHEMA`. */
  requests: GeomapWidgetRequest[];
  style: GeomapWidgetDefinitionStyle;
  view: GeomapWidgetDefinitionView;
  custom_links?: WidgetCustomLink[];
  title?: string;
  title_size?: string;
  title_align?: WidgetTextAlign;
  description?: string;
  time?: WidgetTime;
}
// --- GeomapWidgetDefinitionType ---
type GeomapWidgetDefinitionType = "geomap";
// --- GeomapWidgetRequest ---
interface GeomapWidgetRequest {
  queries?: FormulaAndFunctionQueryDefinition[];
  formulas?: WidgetFormula[];
  response_format?: FormulaAndFunctionResponseFormat;
  sort?: WidgetSortBy;
  columns?: ListStreamColumn[];
  /** Threshold (numeric) conditional formatting rules may be used by a regions layer. */
  conditional_formats?: WidgetConditionalFormat[];
  style?: GeomapWidgetRequestStyle;
  /** Text formatting rules may be used by a points layer. */
  text_formats?: TableWidgetTextFormatRule[];
  query?: ListStreamQuery;
}
// --- GeomapWidgetDefinitionStyle ---
interface GeomapWidgetDefinitionStyle {
  /** e.g. hostmap_blues */
  palette: string;
  palette_flip: boolean;
}
// --- GeomapWidgetDefinitionView ---
interface GeomapWidgetDefinitionView {
  /** The 2-letter ISO code of a country to focus the map on, or `WORLD` for global view, or a region (`EMEA`, `APAC`, `LATAM`), or a continent (`NORTH_AMERICA`, `SOUTH_AMERICA`, `EUROPE`, `AFRICA`, `ASIA`, `OCEANIA`). e.g. WORLD */
  focus: string;
}
// --- WidgetSortBy ---
interface WidgetSortBy {
  /** The number of items to limit the widget to. */
  count?: number;
  order_by?: WidgetSortOrderBy[];
}
// --- ListStreamColumn ---
interface ListStreamColumn {
  width: ListStreamColumnWidth;
  field: string;
}
// --- GeomapWidgetRequestStyle ---
/** Style for points layer. */
interface GeomapWidgetRequestStyle {
  /** The category to color the points by. e.g. status */
  color_by?: string;
}
// --- TableWidgetTextFormatRule ---
interface TableWidgetTextFormatRule {
  match: TableWidgetTextFormatMatch;
  replace?: TableWidgetTextFormatReplace;
  palette?: TableWidgetTextFormatPalette;
  /** Hex representation of the custom background color. Used with custom background palette option. e.g. #632ca6 */
  custom_bg_color?: string;
  /** Hex representation of the custom text color. Used with custom text palette option. e.g. #632ca6 */
  custom_fg_color?: string;
}
// --- ListStreamQuery ---
interface ListStreamQuery {
  /** e.g. @service:app */
  query_string: string;
  data_source: ListStreamSource;
  indexes?: string[];
  event_size?: WidgetEventSize;
  /** Option for storage location. e.g. indexes */
  storage?: string;
  /** Group by can be used only with logs_pattern_stream (up to 4 items) or logs_transaction_stream (one group by item is required) list stream source. */
  group_by?: ListStreamGroupByItems[];
  /** Specifies the field for logs pattern clustering. Usable only with logs_pattern_stream. e.g. message */
  clustering_pattern_field_path?: string;
  /** Compute can be used only with the logs_transaction_stream (from 1 to 5 items) list stream source. */
  compute?: ListStreamComputeItems[];
  sort?: WidgetFieldSort;
  /** Filter by issue states. Usable only with `issue_stream`. */
  states?: ListStreamIssueState[];
  /** Filter by assignee UUIDs. Usable only with `issue_stream`. */
  assignee_uuids?: string[];
  /** Filter by suspected causes. Usable only with `issue_stream`. */
  suspected_causes?: string[];
  /** Filter by team handles. Usable only with `issue_stream`. */
  team_handles?: string[];
  persona?: ListStreamIssuePersona;
}
// --- WidgetSortOrderBy ---
type WidgetSortOrderBy = WidgetFormulaSort | WidgetGroupSort;
// --- ListStreamColumnWidth ---
type ListStreamColumnWidth = "auto" | "compact" | "full";
// --- TableWidgetTextFormatMatch ---
interface TableWidgetTextFormatMatch {
  type: TableWidgetTextFormatMatchType;
  value: string;
}
// --- TableWidgetTextFormatReplace ---
type TableWidgetTextFormatReplace = TableWidgetTextFormatReplaceAll | TableWidgetTextFormatReplaceSubstring;
// --- TableWidgetTextFormatPalette ---
/** @default white_on_green */
type TableWidgetTextFormatPalette = "white_on_red" | "white_on_yellow" | "white_on_green" | "black_on_light_red" | "black_on_light_yellow" | "black_on_light_green" | "red_on_white" | "yellow_on_white" | "green_on_white" | "custom_bg" | "custom_text";
// --- ListStreamSource ---
/** apm_issue_stream, rum_issue_stream, and logs_issue_stream are deprecated. Use issue_stream instead. @default logs_stream */
type ListStreamSource = "logs_stream" | "audit_stream" | "ci_pipeline_stream" | "ci_test_stream" | "rum_issue_stream" | "apm_issue_stream" | "trace_stream" | "logs_issue_stream" | "logs_pattern_stream" | "logs_transaction_stream" | "event_stream" | "rum_stream" | "llm_observability_stream" | "issue_stream";
// --- WidgetEventSize ---
type WidgetEventSize = "s" | "l";
// --- ListStreamGroupByItems ---
interface ListStreamGroupByItems {
  /** e.g. resource_name */
  facet: string;
}
// --- ListStreamComputeItems ---
interface ListStreamComputeItems {
  /** e.g. resource_name */
  facet?: string;
  aggregation: ListStreamComputeAggregation;
}
// --- WidgetFieldSort ---
interface WidgetFieldSort {
  /** Facet path for the column */
  column: string;
  order: WidgetSort;
}
// --- ListStreamIssueState ---
/** Issue state filter for the `issue_stream` data source. */
type ListStreamIssueState = "OPEN" | "IGNORED" | "ACKNOWLEDGED" | "RESOLVED";
// --- ListStreamIssuePersona ---
/** Persona filter for the `issue_stream` data source. */
type ListStreamIssuePersona = "all" | "browser" | "mobile" | "backend";
// --- WidgetFormulaSort ---
interface WidgetFormulaSort {
  type: FormulaType;
  /** The index of the formula to sort by. */
  index: number;
  order: WidgetSort;
}
// --- WidgetGroupSort ---
interface WidgetGroupSort {
  type: GroupType;
  /** The name of the group. */
  name: string;
  order: WidgetSort;
}
// --- TableWidgetTextFormatMatchType ---
type TableWidgetTextFormatMatchType = "is" | "is_not" | "contains" | "does_not_contain" | "starts_with" | "ends_with";
// --- TableWidgetTextFormatReplaceAll ---
interface TableWidgetTextFormatReplaceAll {
  type: TableWidgetTextFormatReplaceAllType;
  /** Replacement string. */
  with: string;
}
// --- TableWidgetTextFormatReplaceSubstring ---
interface TableWidgetTextFormatReplaceSubstring {
  type: TableWidgetTextFormatReplaceSubstringType;
  /** Text that will replace original sub-string. */
  with: string;
  /** Text that will be replaced. */
  substring: string;
}
// --- ListStreamComputeAggregation ---
type ListStreamComputeAggregation = "count" | "cardinality" | "median" | "pc75" | "pc90" | "pc95" | "pc98" | "pc99" | "sum" | "min" | "max" | "avg" | "earliest" | "latest" | "most_frequent";
// --- FormulaType ---
type FormulaType = "formula";
// --- GroupType ---
type GroupType = "group";
// --- TableWidgetTextFormatReplaceAllType ---
type TableWidgetTextFormatReplaceAllType = "all";
// --- TableWidgetTextFormatReplaceSubstringType ---
type TableWidgetTextFormatReplaceSubstringType = "substring";
// --- HeatMapWidgetDefinition ---
interface HeatMapWidgetDefinition {
  markers?: WidgetMarker[];
  type: HeatMapWidgetDefinitionType;
  requests: HeatMapWidgetRequest[];
  xaxis?: HeatMapWidgetXAxis;
  yaxis?: WidgetAxis;
  custom_links?: WidgetCustomLink[];
  title?: string;
  show_legend?: boolean;
  legend_size?: WidgetLegendSize;
  title_size?: string;
  title_align?: WidgetTextAlign;
  description?: string;
  time?: WidgetTime;
}
// --- HeatMapWidgetDefinitionType ---
type HeatMapWidgetDefinitionType = "heatmap";
// --- HeatMapWidgetRequest ---
interface HeatMapWidgetRequest {
  style?: WidgetStyle;
  queries?: FormulaAndFunctionQueryDefinition[];
  formulas?: WidgetFormula[];
  /** Applicable only for distribution of aggregated grouped queries. */
  response_format?: FormulaAndFunctionResponseFormat;
  /** Applicable only for distribution of point values for distribution metrics. */
  request_type?: WidgetHistogramRequestType;
  query?: FormulaAndFunctionMetricQueryDefinition;
}
// --- HeatMapWidgetXAxis ---
interface HeatMapWidgetXAxis {
  /** Number of time buckets to target (resolution of time bins). Only applicable for distribution of points (group distributions use the roll-up modifier). */
  num_buckets?: number;
}
// --- ListStreamWidgetDefinition ---
interface ListStreamWidgetDefinition {
  type: ListStreamWidgetDefinitionType;
  requests: ListStreamWidgetRequest[];
  title?: string;
  show_legend?: boolean;
  legend_size?: WidgetLegendSize;
  title_size?: string;
  title_align?: WidgetTextAlign;
  description?: string;
  time?: WidgetTime;
}
// --- ListStreamWidgetDefinitionType ---
type ListStreamWidgetDefinitionType = "list_stream";
// --- ListStreamWidgetRequest ---
interface ListStreamWidgetRequest {
  columns: ListStreamColumn[];
  query: ListStreamQuery;
  response_format: ListStreamResponseFormat;
}
// --- ListStreamResponseFormat ---
type ListStreamResponseFormat = "event_list";
// --- QueryValueWidgetDefinition ---
interface QueryValueWidgetDefinition {
  type: QueryValueWidgetDefinitionType;
  requests: QueryValueWidgetRequest[];
  /** Whether to use auto-scaling or not. */
  autoscale?: boolean;
  /** Display a unit of your choice on the widget. */
  custom_unit?: string;
  /** Number of decimals to show. If not defined, the widget uses the raw value. */
  precision?: number;
  text_align?: WidgetTextAlign;
  custom_links?: WidgetCustomLink[];
  title?: string;
  title_size?: string;
  title_align?: WidgetTextAlign;
  description?: string;
  time?: WidgetTime;
  timeseries_background?: TimeseriesBackground;
}
// --- QueryValueWidgetDefinitionType ---
type QueryValueWidgetDefinitionType = "query_value";
// --- QueryValueWidgetRequest ---
interface QueryValueWidgetRequest {
  queries?: FormulaAndFunctionQueryDefinition[];
  formulas?: WidgetFormula[];
  response_format?: FormulaAndFunctionResponseFormat;
  conditional_formats?: WidgetConditionalFormat[];
  aggregator?: WidgetAggregator;
  /** Displays a change indicator showing a delta against a historical baseline. */
  comparison?: QueryValueWidgetComparison;
}
// --- TimeseriesBackground ---
/** Set a timeseries on the widget background. */
interface TimeseriesBackground {
  type: TimeseriesBackgroundType;
  yaxis?: WidgetAxis;
}
// --- QueryValueWidgetComparison ---
interface QueryValueWidgetComparison {
  type?: QueryValueWidgetComparisonType;
  /** Which direction of change is considered an improvement, determining the indicator color. */
  directionality?: QueryValueWidgetComparisonDirectionality;
  duration: ComparisonDuration;
}
// --- TimeseriesBackgroundType ---
/** @default area */
type TimeseriesBackgroundType = "bars" | "area";
// --- QueryValueWidgetComparisonType ---
/** How the delta is expressed: `absolute` (raw difference), `relative` (percentage), or `both`. @default absolute */
type QueryValueWidgetComparisonType = "absolute" | "relative" | "both";
// --- QueryValueWidgetComparisonDirectionality ---
/** Color-coding direction: `increase_better` (green on rise), `decrease_better` (green on drop), or `neutral` (no color). @default neutral */
type QueryValueWidgetComparisonDirectionality = "increase_better" | "decrease_better" | "neutral";
// --- ComparisonDuration ---
/** Use a preset `type` value or set `type` to `custom_timeframe` and provide `custom_timeframe` with explicit millisecond epoch bounds. */
interface ComparisonDuration {
  type: ComparisonDurationType;
  /** Required when `type` is `custom_timeframe`. Fixed time range to compare against. */
  custom_timeframe?: ComparisonCustomTimeframe;
}
// --- ComparisonDurationType ---
type ComparisonDurationType = "previous_timeframe" | "custom_timeframe" | "previous_day" | "previous_week" | "previous_month";
// --- ComparisonCustomTimeframe ---
interface ComparisonCustomTimeframe {
  /** Start time in milliseconds since epoch. */
  from: number;
  /** End time in milliseconds since epoch. */
  to: number;
}
// --- SunburstWidgetDefinition ---
interface SunburstWidgetDefinition {
  type: SunburstWidgetDefinitionType;
  requests: (SunburstWidgetRequest | TreeLocalDatasetRequest)[];
  /** Show the total value in this widget. */
  hide_total?: boolean;
  legend?: SunburstWidgetLegend;
  title?: string;
  title_size?: string;
  title_align?: WidgetTextAlign;
  description?: string;
  time?: WidgetTime;
  custom_links?: WidgetCustomLink[];
}
// --- SunburstWidgetDefinitionType ---
type SunburstWidgetDefinitionType = "sunburst";
// --- SunburstWidgetRequest ---
interface SunburstWidgetRequest {
  queries?: FormulaAndFunctionQueryDefinition[];
  formulas?: WidgetFormula[];
  response_format?: FormulaAndFunctionResponseFormat;
  sort?: WidgetSortBy;
  style?: WidgetStyle;
}
// --- SunburstWidgetLegend ---
type SunburstWidgetLegend = SunburstWidgetLegendTable | SunburstWidgetLegendInlineAutomatic;
// --- SunburstWidgetLegendTable ---
interface SunburstWidgetLegendTable {
  type: SunburstWidgetLegendTableType;
}
// --- SunburstWidgetLegendInlineAutomatic ---
interface SunburstWidgetLegendInlineAutomatic {
  type: SunburstWidgetLegendInlineAutomaticType;
  /** Whether to hide the values of the groups. */
  hide_value?: boolean;
  /** Whether to hide the percentages of the groups. */
  hide_percent?: boolean;
}
// --- SunburstWidgetLegendTableType ---
type SunburstWidgetLegendTableType = "table" | "none";
// --- SunburstWidgetLegendInlineAutomaticType ---
type SunburstWidgetLegendInlineAutomaticType = "inline" | "automatic";
// --- TableWidgetDefinition ---
interface TableWidgetDefinition {
  type: TableWidgetDefinitionType;
  requests: (TableWidgetRequest | LocalDatasetRequest)[];
  custom_links?: WidgetCustomLink[];
  has_search_bar?: TableWidgetHasSearchBar;
  title?: string;
  title_size?: string;
  title_align?: WidgetTextAlign;
  description?: string;
  time?: WidgetTime;
}
// --- TableWidgetDefinitionType ---
type TableWidgetDefinitionType = "query_table";
// --- TableWidgetRequest ---
interface TableWidgetRequest {
  apm_stats_query?: ApmStatsQueryDefinition;
  queries?: FormulaAndFunctionQueryDefinition[];
  formulas?: WidgetFormula[];
  response_format?: FormulaAndFunctionResponseFormat;
  /** List of text formats for columns produced by tags. */
  text_formats?: TableWidgetTextFormat[];
  /** The column name (defaults to the metric name). */
  alias?: string;
  aggregator?: WidgetAggregator;
  /** For metric queries, the number of lines to show in the table. Only one request should have this property. */
  limit?: number;
  order?: WidgetSort;
  conditional_formats?: WidgetConditionalFormat[];
  cell_display_mode?: TableWidgetCellDisplayMode[];
  sort?: WidgetSortBy;
}
// --- TableWidgetHasSearchBar ---
/** Controls the display of the search bar. */
type TableWidgetHasSearchBar = "always" | "never" | "auto";
// --- TableWidgetTextFormat ---
type TableWidgetTextFormat = TableWidgetTextFormatRule[];
// --- ToplistWidgetDefinition ---
interface ToplistWidgetDefinition {
  type: ToplistWidgetDefinitionType;
  requests: (ToplistWidgetRequest | TreeLocalDatasetRequest)[];
  style?: ToplistWidgetStyle;
  custom_links?: WidgetCustomLink[];
  title?: string;
  title_size?: string;
  title_align?: WidgetTextAlign;
  description?: string;
  time?: WidgetTime;
}
// --- ToplistWidgetDefinitionType ---
type ToplistWidgetDefinitionType = "toplist";
// --- ToplistWidgetRequest ---
interface ToplistWidgetRequest {
  queries?: FormulaAndFunctionQueryDefinition[];
  formulas?: WidgetFormula[];
  response_format?: FormulaAndFunctionResponseFormat;
  sort?: WidgetSortBy;
  style?: WidgetRequestStyle;
  conditional_formats?: WidgetConditionalFormat[];
}
// --- ToplistWidgetStyle ---
interface ToplistWidgetStyle {
  display?: ToplistWidgetDisplay;
  scaling?: ToplistWidgetScaling;
  palette?: string;
}
// --- WidgetRequestStyle ---
interface WidgetRequestStyle {
  palette?: string;
  line_type?: WidgetLineType;
  line_width?: WidgetLineWidth;
  order_by?: WidgetStyleOrderBy;
}
// --- ToplistWidgetDisplay ---
type ToplistWidgetDisplay = ToplistWidgetStacked | ToplistWidgetFlat;
// --- ToplistWidgetScaling ---
type ToplistWidgetScaling = "absolute" | "relative";
// --- ToplistWidgetStacked ---
interface ToplistWidgetStacked {
  type: ToplistWidgetStackedType;
  legend?: ToplistWidgetLegend;
}
// --- ToplistWidgetFlat ---
interface ToplistWidgetFlat {
  type: ToplistWidgetFlatType;
}
// --- ToplistWidgetStackedType ---
type ToplistWidgetStackedType = "stacked";
// --- ToplistWidgetLegend ---
type ToplistWidgetLegend = "automatic" | "inline" | "none";
// --- ToplistWidgetFlatType ---
type ToplistWidgetFlatType = "flat";
// --- TreeMapWidgetDefinition ---
interface TreeMapWidgetDefinition {
  type: TreeMapWidgetDefinitionType;
  requests: (TreeMapWidgetRequest | TreeLocalDatasetRequest)[];
  title?: string;
  description?: string;
  custom_links?: WidgetCustomLink[];
  time?: WidgetTime;
}
// --- TreeMapWidgetDefinitionType ---
type TreeMapWidgetDefinitionType = "treemap";
// --- TreeMapWidgetRequest ---
interface TreeMapWidgetRequest {
  queries?: FormulaAndFunctionQueryDefinition[];
  formulas?: WidgetFormula[];
  response_format?: FormulaAndFunctionResponseFormat;
  sort?: WidgetSortBy;
  style?: WidgetRequestStyle;
}
// --- BarChartWidgetDefinition ---
interface BarChartWidgetDefinition {
  type: BarChartWidgetDefinitionType;
  requests: (BarChartWidgetRequest | TreeLocalDatasetRequest)[];
  style?: BarChartWidgetStyle;
  custom_links?: WidgetCustomLink[];
  title?: string;
  title_size?: string;
  title_align?: WidgetTextAlign;
  description?: string;
  time?: WidgetTime;
}
// --- BarChartWidgetDefinitionType ---
type BarChartWidgetDefinitionType = "bar_chart";
// --- BarChartWidgetRequest ---
interface BarChartWidgetRequest {
  queries?: FormulaAndFunctionQueryDefinition[];
  formulas?: WidgetFormula[];
  response_format?: FormulaAndFunctionResponseFormat;
  sort?: WidgetSortBy;
  style?: WidgetRequestStyle;
  conditional_formats?: WidgetConditionalFormat[];
}
// --- BarChartWidgetStyle ---
interface BarChartWidgetStyle {
  display?: BarChartWidgetDisplay;
  scaling?: BarChartWidgetScaling;
  palette?: string;
}
// --- BarChartWidgetDisplay ---
type BarChartWidgetDisplay = BarChartWidgetStacked | BarChartWidgetFlat;
// --- BarChartWidgetScaling ---
type BarChartWidgetScaling = "absolute" | "relative";
// --- BarChartWidgetStacked ---
interface BarChartWidgetStacked {
  type: BarChartWidgetStackedType;
  legend?: BarChartWidgetLegend;
}
// --- BarChartWidgetFlat ---
interface BarChartWidgetFlat {
  type: BarChartWidgetFlatType;
}
// --- BarChartWidgetStackedType ---
type BarChartWidgetStackedType = "stacked";
// --- BarChartWidgetLegend ---
type BarChartWidgetLegend = "automatic" | "inline" | "none";
// --- BarChartWidgetFlatType ---
type BarChartWidgetFlatType = "flat";
// --- ChangeWidgetDefinition ---
interface ChangeWidgetDefinition {
  type: ChangeWidgetDefinitionType;
  /** Array of one request object to display in the widget. See the dedicated [Request JSON schema documentation](https://docs.datadoghq.com/dashboards/graphing_json/request_json) to learn how to build the `REQUEST_SCHEMA`. e.g. [ { "q": "<METRIC_1>{<SCOPE_1>}" } ] */
  requests: ChangeWidgetRequest[];
  custom_links?: WidgetCustomLink[];
  title?: string;
  title_size?: string;
  title_align?: WidgetTextAlign;
  description?: string;
  time?: WidgetTime;
}
// --- ChangeWidgetDefinitionType ---
type ChangeWidgetDefinitionType = "change";
// --- ChangeWidgetRequest ---
interface ChangeWidgetRequest {
  queries?: FormulaAndFunctionQueryDefinition[];
  formulas?: WidgetFormula[];
  response_format?: FormulaAndFunctionResponseFormat;
  change_type?: WidgetChangeType;
  compare_to?: WidgetCompareTo;
  /** Whether to show increase as good. */
  increase_good?: boolean;
  order_by?: WidgetOrderBy;
  order_dir?: WidgetSort;
  show_present?: boolean;
}
// --- WidgetChangeType ---
/** Show the absolute or the relative change. */
type WidgetChangeType = "absolute" | "relative";
// --- WidgetCompareTo ---
/** Timeframe used for the change comparison. */
type WidgetCompareTo = "hour_before" | "day_before" | "week_before" | "month_before";
// --- WidgetOrderBy ---
type WidgetOrderBy = "change" | "name" | "present" | "past";
// --- FunnelWidgetDefinition ---
interface FunnelWidgetDefinition {
  type: FunnelWidgetDefinitionType;
  /** Request payload used to query items. e.g. [ { "request_type": "funnel", "query": { "data_source": "rum", "query_string": "@browser.name:Chrome", "steps": [ { "facet": "@view.name", "value": "/logs" }, { "facet": "@view.name", "value": "/apm/home" } ] } } ] */
  requests: FunnelWidgetRequest[];
  title?: string;
  title_size?: string;
  title_align?: WidgetTextAlign;
  description?: string;
  time?: WidgetTime;
  grouped_display?: FunnelGroupedDisplay;
}
// --- FunnelWidgetDefinitionType ---
type FunnelWidgetDefinitionType = "funnel";
// --- FunnelWidgetRequest ---
interface FunnelWidgetRequest {
  query: FunnelQuery;
  request_type: FunnelRequestType;
}
// --- FunnelGroupedDisplay ---
type FunnelGroupedDisplay = "stacked" | "side_by_side";
// --- FunnelQuery ---
interface FunnelQuery {
  /** The widget query. e.g. @browser.name:Chrome */
  query_string: string;
  data_source: FunnelSource;
  steps: FunnelStep[];
}
// --- FunnelRequestType ---
type FunnelRequestType = "funnel";
// --- FunnelSource ---
type FunnelSource = "rum";
// --- FunnelStep ---
interface FunnelStep {
  /** The facet of the step. e.g. @view.name */
  facet: string;
  /** The value of the step. e.g. /apm/home */
  value: string;
}
// --- ProductAnalyticsFunnelWidgetDefinition ---
interface ProductAnalyticsFunnelWidgetDefinition {
  type: FunnelWidgetDefinitionType;
  /** Request payload used to query items. e.g. [ { "request_type": "user_journey_funnel", "query": { "data_source": "product_analytics_journey", "search": { "node_objects": { "step1": { "data_source": "product_analytics", "search": { "query": "@type:view @view.name:/home" } }, "step2": { "data_source": "product_analytics", "search": { "query": "@type:action @action.name:\"add to cart\"" } } }, "expression": "step1 -> step2", "filters": { "string_filter": "@application.id:xxx @geo.country:France" } }, "compute": { "metric": "__dd.conversion", "aggregation": "cardinality" } } } ] */
  requests: ProductAnalyticsFunnelRequest[];
  title?: string;
  title_size?: string;
  title_align?: WidgetTextAlign;
  description?: string;
  time?: WidgetTime;
  grouped_display?: FunnelGroupedDisplay;
}
// --- ProductAnalyticsFunnelRequest ---
interface ProductAnalyticsFunnelRequest {
  query: ProductAnalyticsFunnelQuery;
  request_type: ProductAnalyticsFunnelRequestType;
  comparison_time?: FunnelComparisonDuration;
  comparison_segments?: string[];
}
// --- ProductAnalyticsFunnelQuery ---
interface ProductAnalyticsFunnelQuery {
  data_source: ProductAnalyticsFunnelDataSource;
  search: UserJourneySearch;
  subquery_id?: string;
  group_by?: ProductAnalyticsFunnelGroupBy[];
  compute?: ProductAnalyticsFunnelCompute;
}
// --- ProductAnalyticsFunnelRequestType ---
type ProductAnalyticsFunnelRequestType = "user_journey_funnel";
// --- FunnelComparisonDuration ---
interface FunnelComparisonDuration {
  type: FunnelComparisonDurationType;
  custom_timeframe?: FunnelComparisonCustomTimeframe;
}
// --- ProductAnalyticsFunnelGroupBy ---
interface ProductAnalyticsFunnelGroupBy {
  /** Facet to group by. e.g. @usr.email */
  facet: string;
  /** Maximum number of groups. */
  limit?: number;
  sort?: ProductAnalyticsFunnelGroupBySort;
  should_exclude_missing?: boolean;
  target?: UserJourneySearchTarget;
}
// --- ProductAnalyticsFunnelCompute ---
interface ProductAnalyticsFunnelCompute {
  aggregation: ProductAnalyticsFunnelComputeAggregation;
  metric: ProductAnalyticsFunnelComputeMetric;
}
// --- FunnelComparisonDurationType ---
type FunnelComparisonDurationType = "previous_timeframe" | "custom_timeframe" | "previous_day" | "previous_week" | "previous_month";
// --- FunnelComparisonCustomTimeframe ---
interface FunnelComparisonCustomTimeframe {
  /** Start of the custom timeframe. */
  from: number;
  /** End of the custom timeframe. */
  to: number;
}
// --- ProductAnalyticsFunnelGroupBySort ---
interface ProductAnalyticsFunnelGroupBySort {
  /** Metric to sort by. e.g. @session.id */
  metric?: string;
  /** Aggregation type. e.g. count */
  aggregation: string;
  order?: WidgetSort;
}
// --- ProductAnalyticsFunnelComputeAggregation ---
type ProductAnalyticsFunnelComputeAggregation = "cardinality" | "count";
// --- ProductAnalyticsFunnelComputeMetric ---
/** `__dd.conversion` and `__dd.conversion_rate` accept `count` (unique users/sessions) and `cardinality` (total users/sessions) as aggregations. */
type ProductAnalyticsFunnelComputeMetric = "__dd.conversion" | "__dd.conversion_rate";
// --- CohortWidgetDefinition ---
interface CohortWidgetDefinition {
  type: CohortWidgetDefinitionType;
  requests: RetentionGridRequest[];
  title?: string;
  title_size?: string;
  title_align?: WidgetTextAlign;
  description?: string;
  time?: WidgetTime;
}
// --- CohortWidgetDefinitionType ---
type CohortWidgetDefinitionType = "cohort";
// --- RetentionGridRequest ---
interface RetentionGridRequest {
  request_type: RetentionGridRequestType;
  query: RetentionQuery;
}
// --- RetentionGridRequestType ---
type RetentionGridRequestType = "retention_grid";
// --- RetentionQuery ---
interface RetentionQuery {
  name?: string;
  data_source: RetentionDataSource;
  search: RetentionSearch;
  compute: RetentionCompute;
  group_by?: RetentionGroupBy[];
  filters?: RetentionFilters;
}
// --- RetentionCurveWidgetDefinition ---
interface RetentionCurveWidgetDefinition {
  type: RetentionCurveWidgetDefinitionType;
  requests: RetentionCurveWidgetRequest[];
  title?: string;
  title_size?: string;
  title_align?: WidgetTextAlign;
  description?: string;
  time?: WidgetTime;
}
// --- RetentionCurveWidgetDefinitionType ---
type RetentionCurveWidgetDefinitionType = "retention_curve";
// --- RetentionCurveWidgetRequest ---
interface RetentionCurveWidgetRequest {
  request_type: RetentionCurveRequestType;
  query: RetentionQuery;
  style?: RetentionCurveStyle;
}
// --- RetentionCurveRequestType ---
type RetentionCurveRequestType = "retention_curve";
// --- RetentionCurveStyle ---
interface RetentionCurveStyle {
  palette?: string;
}
// --- SankeyWidgetDefinition ---
interface SankeyWidgetDefinition {
  type: SankeyWidgetDefinitionType;
  requests: SankeyWidgetRequest[];
  /** Whether to sort nodes in the Sankey diagram. */
  sort_nodes?: boolean;
  /** Whether to show links for "other" category. */
  show_other_links?: boolean;
  title?: string;
  title_size?: string;
  title_align?: WidgetTextAlign;
  time?: WidgetTime;
}
// --- SankeyWidgetDefinitionType ---
type SankeyWidgetDefinitionType = "sankey";
// --- SankeyWidgetRequest ---
type SankeyWidgetRequest = SankeyRumRequest | SankeyNetworkRequest;
// --- SankeyRumRequest ---
/** Sankey widget request for Product Analytics or RUM data source. */
interface SankeyRumRequest {
  query: SankeyRumQuery;
  request_type: SankeyWidgetDefinitionType;
}
// --- SankeyNetworkRequest ---
/** Sankey widget request for network data source. */
interface SankeyNetworkRequest {
  query: SankeyNetworkQuery;
  request_type: SankeyNetworkRequestType;
}
// --- SankeyRumQuery ---
interface SankeyRumQuery {
  data_source: SankeyRumDataSource;
  /** RUM event search query used to filter views or actions. e.g. @type:view */
  query_string: string;
  entries_per_step?: number;
  subquery_id?: string;
  mode: SankeyRumQueryMode;
  source?: string;
  target?: string;
  number_of_steps?: number;
  audience_filters?: ProductAnalyticsAudienceFilters;
  occurrences?: ProductAnalyticsAudienceOccurrenceFilter;
  join_keys?: SankeyJoinKeys;
}
// --- SankeyNetworkQuery ---
interface SankeyNetworkQuery {
  data_source: SankeyNetworkDataSource;
  /** Query string for filtering network data. e.g. * */
  query_string: string;
  mode?: SankeyNetworkQueryMode;
  group_by: string[];
  limit: number;
  sort?: SankeyNetworkQuerySort;
  compute?: SankeyNetworkQueryCompute;
  should_exclude_missing?: boolean;
}
// --- SankeyNetworkRequestType ---
type SankeyNetworkRequestType = "netflow_sankey";
// --- SankeyRumDataSource ---
/** @default product_analytics */
type SankeyRumDataSource = "rum" | "product_analytics";
// --- SankeyRumQueryMode ---
/** @default source */
type SankeyRumQueryMode = "source" | "target";
// --- ProductAnalyticsAudienceOccurrenceFilter ---
interface ProductAnalyticsAudienceOccurrenceFilter {
  /** The comparison operator (e.g. `gt`, `lt`, `eq`). */
  operator?: string;
  /** The threshold value to compare occurrence counts against. */
  value?: string;
}
// --- SankeyJoinKeys ---
interface SankeyJoinKeys {
  /** e.g. session.id */
  primary: string;
  secondary?: string[];
}
// --- SankeyNetworkDataSource ---
/** @default network */
type SankeyNetworkDataSource = "network_device_flows" | "network";
// --- SankeyNetworkQueryMode ---
type SankeyNetworkQueryMode = "target";
// --- SankeyNetworkQuerySort ---
interface SankeyNetworkQuerySort {
  field?: string;
  order?: WidgetSort;
}
// --- SankeyNetworkQueryCompute ---
interface SankeyNetworkQueryCompute {
  aggregation: EventsAggregation;
  metric: string;
}
// --- ScatterPlotWidgetDefinition ---
interface ScatterPlotWidgetDefinition {
  type: ScatterPlotWidgetDefinitionType;
  requests: ScatterPlotWidgetDefinitionRequests;
  xaxis?: WidgetAxis;
  yaxis?: WidgetAxis;
  /** List of groups used for colors. */
  color_by_groups?: string[];
  custom_links?: WidgetCustomLink[];
  title?: string;
  title_size?: string;
  title_align?: WidgetTextAlign;
  description?: string;
  time?: WidgetTime;
}
// --- ScatterPlotWidgetDefinitionType ---
type ScatterPlotWidgetDefinitionType = "scatterplot";
// --- ScatterPlotWidgetDefinitionRequests ---
interface ScatterPlotWidgetDefinitionRequests {
  x?: ScatterPlotRequest | LocalDatasetRequest;
  y?: ScatterPlotRequest | LocalDatasetRequest;
  table?: ScatterplotTableRequest | LocalDatasetRequest;
}
// --- ScatterPlotRequest ---
interface ScatterPlotRequest {
  /** Query definition. */
  q?: string;
  aggregator?: ScatterplotWidgetAggregator;
}
// --- ScatterplotTableRequest ---
/** Scatterplot request containing formulas and functions. */
interface ScatterplotTableRequest {
  response_format?: FormulaAndFunctionResponseFormat;
  /** List of queries that can be returned directly or used in formulas. */
  queries?: FormulaAndFunctionQueryDefinition[];
  /** List of Scatterplot formulas that operate on queries. */
  formulas?: ScatterplotWidgetFormula[];
}
// --- ScatterplotWidgetAggregator ---
type ScatterplotWidgetAggregator = "avg" | "last" | "max" | "min" | "sum";
// --- ScatterplotWidgetFormula ---
interface ScatterplotWidgetFormula {
  /** String expression built from queries, formulas, and functions. e.g. func(a) + b */
  formula: string;
  /** Expression alias. */
  alias?: string;
  dimension: ScatterplotDimension;
}
// --- ScatterplotDimension ---
type ScatterplotDimension = "x" | "y" | "radius" | "color";
// --- WildcardWidgetDefinition ---
interface WildcardWidgetDefinition {
  type: WildcardWidgetDefinitionType;
  requests: (WildcardWidgetRequest | LocalDatasetRequest)[];
  specification: WildcardWidgetSpecification;
  custom_links?: WidgetCustomLink[];
  title?: string;
  title_size?: string;
  title_align?: WidgetTextAlign;
  time?: WidgetTime;
}
// --- WildcardWidgetDefinitionType ---
type WildcardWidgetDefinitionType = "wildcard";
// --- WildcardWidgetRequest ---
/** Each variant represents a distinct data-fetching pattern: scalar formulas, timeseries formulas, list streams, and histograms. */
type WildcardWidgetRequest = TreeMapWidgetRequest | TimeseriesWidgetRequest | ListStreamWidgetRequest | DistributionWidgetRequest;
// --- WildcardWidgetSpecification ---
/** Vega or Vega-Lite specification for custom visualization rendering. See https://vega.github.io/vega-lite/ for the full grammar reference. */
interface WildcardWidgetSpecification {
  type: WildcardWidgetSpecificationType;
  /** The Vega or Vega-Lite JSON specification object. */
  contents: Record<string, unknown>;
}
// --- WildcardWidgetSpecificationType ---
type WildcardWidgetSpecificationType = "vega" | "vega-lite";
// --- AlertGraphWidgetDefinition ---
interface AlertGraphWidgetDefinition {
  type: AlertGraphWidgetDefinitionType;
  /** ID of the alert to use in the widget. */
  alert_id: string;
  viz_type: WidgetVizType;
  title?: string;
  title_size?: string;
  title_align?: WidgetTextAlign;
  description?: string;
  time?: WidgetTime;
}
// --- AlertGraphWidgetDefinitionType ---
type AlertGraphWidgetDefinitionType = "alert_graph";
// --- WidgetVizType ---
/** Whether to display the Alert Graph as a timeseries or a top list. */
type WidgetVizType = "timeseries" | "toplist";
// --- AlertValueWidgetDefinition ---
interface AlertValueWidgetDefinition {
  type: AlertValueWidgetDefinitionType;
  /** ID of the alert to use in the widget. */
  alert_id: string;
  /** Number of decimal to show. If not defined, will use the raw value. */
  precision?: number;
  /** Unit to display with the value. */
  unit?: string;
  /** Size of value in the widget. */
  title_size?: string;
  text_align?: WidgetTextAlign;
  title?: string;
  title_align?: WidgetTextAlign;
  description?: string;
}
// --- AlertValueWidgetDefinitionType ---
type AlertValueWidgetDefinitionType = "alert_value";
// --- CheckStatusWidgetDefinition ---
interface CheckStatusWidgetDefinition {
  type: CheckStatusWidgetDefinitionType;
  /** Name of the check to use in the widget. */
  check: string;
  grouping: WidgetGrouping;
  /** Group reporting a single check. */
  group?: string;
  /** List of tags used to filter the groups reporting a cluster check. */
  tags?: string[];
  /** List of tag prefixes to group by in the case of a cluster check. */
  group_by?: string[];
  title?: string;
  title_size?: string;
  title_align?: WidgetTextAlign;
  description?: string;
  time?: WidgetTime;
}
// --- CheckStatusWidgetDefinitionType ---
type CheckStatusWidgetDefinitionType = "check_status";
// --- WidgetGrouping ---
type WidgetGrouping = "check" | "cluster";
// --- HostMapWidgetDefinition ---
interface HostMapWidgetDefinition {
  type: HostMapWidgetDefinitionType;
  requests: HostMapWidgetDefinitionRequests;
  node_type?: WidgetNodeType;
  no_metric_hosts?: boolean;
  /** Whether to show the hosts that don't fit in a group. */
  no_group_hosts?: boolean;
  /** List of tag prefixes to group by. */
  group?: string[];
  /** List of tags used to filter the map. */
  scope?: string[];
  style?: HostMapWidgetDefinitionStyle;
  custom_links?: WidgetCustomLink[];
  title?: string;
  title_size?: string;
  title_align?: WidgetTextAlign;
  description?: string;
  /** Notes on the title. */
  notes?: string;
}
// --- HostMapWidgetDefinitionType ---
type HostMapWidgetDefinitionType = "hostmap";
// --- HostMapWidgetDefinitionRequests ---
/** Either the metric-based fill/size format or the infrastructure-backed format where request_type implies node_type and enrichments are required. */
type HostMapWidgetDefinitionRequests = MetricHostmapRequests | HostMapWidgetInfrastructureRequest;
// --- WidgetNodeType ---
type WidgetNodeType = "host" | "container";
// --- HostMapWidgetDefinitionStyle ---
interface HostMapWidgetDefinitionStyle {
  palette?: string;
  palette_flip?: boolean;
  /** Min value to use to color the map. */
  fill_min?: string;
  /** Max value to use to color the map. */
  fill_max?: string;
}
// --- HostMapRequest ---
interface HostMapRequest {
  /** Query definition. */
  q?: string;
}
// --- HostMapWidgetInfrastructureRequestRequestType ---
type HostMapWidgetInfrastructureRequestRequestType = "infrastructure_hostmap";
// --- HostMapWidgetNodeType ---
type HostMapWidgetNodeType = "host" | "container" | "pod" | "cluster";
// --- HostMapWidgetGroupBy ---
interface HostMapWidgetGroupBy {
  /** Column name from the entity table (e.g. `cloud_provider`, `tags`, `labels`). */
  column: string;
  /** Key within the column for nested attribute types (e.g. `service` within `tags`). */
  key?: string;
}
// --- HostMapWidgetScalarRequest ---
interface HostMapWidgetScalarRequest {
  response_format: HostMapWidgetScalarRequestResponseFormat;
  queries: FormulaAndFunctionQueryDefinition[];
  /** List of formulas that operate on queries, each assigned to a visual dimension. */
  formulas: HostMapWidgetFormula[];
}
// --- HostMapWidgetInfrastructureStyle ---
interface HostMapWidgetInfrastructureStyle {
  /** Color palette name or alias. e.g. hostmap_blues */
  palette?: string;
  palette_flip?: boolean;
  /** Minimum value for the fill color scale. Omit to use automatic scaling. */
  fill_min?: number;
  /** Maximum value for the fill color scale. Omit to use automatic scaling. */
  fill_max?: number;
}
// --- HostMapWidgetInfrastructureRequest ---
interface HostMapWidgetInfrastructureRequest {
  request_type: HostMapWidgetInfrastructureRequestRequestType;
  node_type: HostMapWidgetNodeType;
  /** Filter string in tag format (e.g. `env:prod`). */
  filter?: string;
  /** Defines how entities are grouped into tiles. The ordering implies the grouping hierarchy. */
  group_by?: HostMapWidgetGroupBy[];
  /** Metric or event queries joined to the entity set. Each formula specifies a visual dimension. */
  enrichments: HostMapWidgetScalarRequest[];
  style?: HostMapWidgetInfrastructureStyle;
  conditional_formats?: WidgetConditionalFormat[];
  no_group_hosts?: boolean;
  no_metric_hosts?: boolean;
  /** Optional child request for hierarchical visualization (e.g. hosts containing containers). Maximum one level of nesting. */
  child?: HostMapWidgetInfrastructureRequestLeaf;
}
// --- HostMapWidgetScalarRequestResponseFormat ---
type HostMapWidgetScalarRequestResponseFormat = "scalar";
// --- HostMapWidgetFormula ---
/** Formula that specifies both the expression and the visual dimension it populates. */
interface HostMapWidgetFormula {
  /** String expression built from queries, formulas, and functions. */
  formula: string;
  alias?: string;
  number_format?: WidgetNumberFormat;
  dimension: HostMapWidgetDimension;
}
// --- HostMapWidgetInfrastructureRequestLeaf ---
/** Child request (leaf node, no further nesting supported). */
interface HostMapWidgetInfrastructureRequestLeaf {
  request_type: HostMapWidgetInfrastructureRequestRequestType;
  node_type: HostMapWidgetNodeType;
  /** Filter string in tag format (e.g. `env:prod`). */
  filter?: string;
  /** Defines how entities are grouped into tiles. The ordering implies the grouping hierarchy. */
  group_by?: HostMapWidgetGroupBy[];
  /** Metric or event queries joined to the entity set. Each formula specifies a visual dimension. */
  enrichments: HostMapWidgetScalarRequest[];
  style?: HostMapWidgetInfrastructureStyle;
  conditional_formats?: WidgetConditionalFormat[];
  no_group_hosts?: boolean;
  no_metric_hosts?: boolean;
}
// --- HostMapWidgetDimension ---
type HostMapWidgetDimension = "node" | "fill" | "size";
// --- MonitorSummaryWidgetDefinition ---
interface MonitorSummaryWidgetDefinition {
  type: MonitorSummaryWidgetDefinitionType;
  /** Query to filter the monitors with. */
  query: string;
  sort?: WidgetMonitorSummarySort;
  summary_type?: WidgetSummaryType;
  display_format?: WidgetMonitorSummaryDisplayFormat;
  color_preference?: WidgetColorPreference;
  hide_zero_counts?: boolean;
  /** Whether to show the time that has elapsed since the monitor/group triggered. */
  show_last_triggered?: boolean;
  title?: string;
  title_size?: string;
  title_align?: WidgetTextAlign;
  description?: string;
  /** Whether to show the priorities column. @default false */
  show_priority: boolean;
}
// --- MonitorSummaryWidgetDefinitionType ---
type MonitorSummaryWidgetDefinitionType = "manage_status";
// --- WidgetMonitorSummarySort ---
type WidgetMonitorSummarySort = "name" | "group" | "status" | "tags" | "triggered" | "group,asc" | "group,desc" | "name,asc" | "name,desc" | "status,asc" | "status,desc" | "tags,asc" | "tags,desc" | "triggered,asc" | "triggered,desc" | "priority,asc" | "priority,desc";
// --- WidgetSummaryType ---
type WidgetSummaryType = "monitors" | "groups" | "combined";
// --- WidgetMonitorSummaryDisplayFormat ---
type WidgetMonitorSummaryDisplayFormat = "counts" | "countsAndList" | "list";
// --- WidgetColorPreference ---
type WidgetColorPreference = "background" | "text";
// --- SLOWidgetDefinition ---
interface SLOWidgetDefinition {
  type: SLOWidgetDefinitionType;
  /** Type of view displayed by the widget. @default detail */
  view_type: string;
  title?: string;
  title_size?: string;
  title_align?: WidgetTextAlign;
  description?: string;
  /** ID of the SLO displayed. */
  slo_id?: string;
  /** Defined error budget. */
  show_error_budget?: boolean;
  view_mode?: WidgetViewMode;
  /** Defined global time target. */
  global_time_target?: string;
  /** Times being monitored. */
  time_windows?: WidgetTimeWindows[];
  /** Additional filters applied to the SLO query. */
  additional_query_filters?: string;
}
// --- SLOWidgetDefinitionType ---
type SLOWidgetDefinitionType = "slo";
// --- WidgetViewMode ---
/** Define how you want the SLO to be displayed. */
type WidgetViewMode = "overall" | "component" | "both";
// --- WidgetTimeWindows ---
type WidgetTimeWindows = "7d" | "30d" | "90d" | "week_to_date" | "previous_week" | "month_to_date" | "previous_month" | "global_time";
// --- SLOListWidgetDefinition ---
interface SLOListWidgetDefinition {
  type: SLOListWidgetDefinitionType;
  /** Array of one request object to display in the widget. */
  requests: SLOListWidgetRequest[];
  title?: string;
  title_size?: string;
  title_align?: WidgetTextAlign;
  description?: string;
}
// --- SLOListWidgetDefinitionType ---
type SLOListWidgetDefinitionType = "slo_list";
// --- SLOListWidgetRequest ---
interface SLOListWidgetRequest {
  query: SLOListWidgetQuery;
  request_type: SLOListWidgetRequestType;
}
// --- SLOListWidgetQuery ---
interface SLOListWidgetQuery {
  /** Widget query. e.g. env:prod AND service:my-app */
  query_string: string;
  /** @default 100 */
  limit: number;
  sort?: WidgetFieldSort[];
}
// --- SLOListWidgetRequestType ---
type SLOListWidgetRequestType = "slo_list";
// --- RunWorkflowWidgetDefinition ---
interface RunWorkflowWidgetDefinition {
  type: RunWorkflowWidgetDefinitionType;
  /** Workflow id. */
  workflow_id: string;
  /** Array of workflow inputs to map to dashboard template variables. */
  inputs?: RunWorkflowWidgetInput[];
  custom_links?: WidgetCustomLink[];
  title?: string;
  title_size?: string;
  title_align?: WidgetTextAlign;
  description?: string;
  time?: WidgetTime;
}
// --- RunWorkflowWidgetDefinitionType ---
type RunWorkflowWidgetDefinitionType = "run_workflow";
// --- RunWorkflowWidgetInput ---
/** Object to map a dashboard template variable to a workflow input. */
interface RunWorkflowWidgetInput {
  /** Name of the workflow input. e.g. Environment */
  name: string;
  /** Dashboard template variable. Can be suffixed with '.value' or '.key'. e.g. $env.value */
  value: string;
}
// --- ServiceMapWidgetDefinition ---
interface ServiceMapWidgetDefinition {
  type: ServiceMapWidgetDefinitionType;
  /** Your environment and primary tag (or * if enabled for your account). e.g. [ "*" ] */
  filters: string[];
  /** The ID of the service you want to map. */
  service: string;
  custom_links?: WidgetCustomLink[];
  title?: string;
  title_size?: string;
  title_align?: WidgetTextAlign;
  description?: string;
}
// --- ServiceMapWidgetDefinitionType ---
type ServiceMapWidgetDefinitionType = "servicemap";
// --- ServiceSummaryWidgetDefinition ---
interface ServiceSummaryWidgetDefinition {
  type: ServiceSummaryWidgetDefinitionType;
  /** APM environment. */
  env: string;
  /** APM service. */
  service: string;
  /** APM span name. */
  span_name: string;
  show_hits?: boolean;
  show_errors?: boolean;
  show_latency?: boolean;
  show_breakdown?: boolean;
  show_distribution?: boolean;
  show_resource_list?: boolean;
  size_format?: WidgetSizeFormat;
  display_format?: WidgetServiceSummaryDisplayFormat;
  title?: string;
  title_size?: string;
  title_align?: WidgetTextAlign;
  description?: string;
  time?: WidgetTime;
}
// --- ServiceSummaryWidgetDefinitionType ---
type ServiceSummaryWidgetDefinitionType = "trace_service";
// --- WidgetSizeFormat ---
type WidgetSizeFormat = "small" | "medium" | "large";
// --- WidgetServiceSummaryDisplayFormat ---
/** Number of columns to display. */
type WidgetServiceSummaryDisplayFormat = "one_column" | "two_column" | "three_column";
// --- TopologyMapWidgetDefinition ---
/** Replaces the service map widget. */
interface TopologyMapWidgetDefinition {
  type: TopologyMapWidgetDefinitionType;
  requests: TopologyRequest[];
  title?: string;
  title_size?: string;
  title_align?: WidgetTextAlign;
  description?: string;
  custom_links?: WidgetCustomLink[];
}
// --- TopologyMapWidgetDefinitionType ---
type TopologyMapWidgetDefinitionType = "topology_map";
// --- TopologyRequest ---
interface TopologyRequest {
  request_type?: TopologyRequestType;
  query?: TopologyQuery;
}
// --- TopologyRequestType ---
type TopologyRequestType = "topology";
// --- TopologyQuery ---
/** Query to service-based topology data sources like the service map or data streams. */
interface TopologyQuery {
  data_source?: TopologyQueryDataSource;
  /** Name of the service e.g. myService */
  service?: string;
  /** Your environment and primary tag (or * if enabled for your account). e.g. [ "env:prod", "az:us-east" ] */
  filters?: string[];
}
// --- TopologyQueryDataSource ---
type TopologyQueryDataSource = "data_streams" | "service_map";
// --- FreeTextWidgetDefinition ---
interface FreeTextWidgetDefinition {
  type: FreeTextWidgetDefinitionType;
  /** Text to display. */
  text: string;
  color?: string;
  /** Size of the text. */
  font_size?: string;
  text_align?: WidgetTextAlign;
  background_color?: WidgetBackgroundColor;
}
// --- FreeTextWidgetDefinitionType ---
type FreeTextWidgetDefinitionType = "free_text";
// --- WidgetBackgroundColor ---
/** Supported values: `white`, `blue`, `purple`, `pink`, `orange`, `yellow`, `green`, `gray`, `vivid_blue`, `vivid_purple`, `vivid_pink`, `vivid_orange`, `vivid_yellow`, `vivid_green`, and `transparent`. */
type WidgetBackgroundColor = string;
// --- NoteWidgetDefinition ---
interface NoteWidgetDefinition {
  type: NoteWidgetDefinitionType;
  /** Content of the note. */
  content: string;
  background_color?: string;
  /** Size of the text. */
  font_size?: string;
  text_align?: WidgetTextAlign;
  vertical_align?: WidgetVerticalAlign;
  /** @default true */
  has_padding: boolean;
  show_tick?: boolean;
  /** Where to position the tick on an edge. */
  tick_pos?: string;
  tick_edge?: WidgetTickEdge;
}
// --- NoteWidgetDefinitionType ---
type NoteWidgetDefinitionType = "note";
// --- WidgetVerticalAlign ---
type WidgetVerticalAlign = "center" | "top" | "bottom";
// --- WidgetTickEdge ---
/** Define how you want to align the text on the widget. */
type WidgetTickEdge = "bottom" | "left" | "right" | "top";
// --- ImageWidgetDefinition ---
interface ImageWidgetDefinition {
  type: ImageWidgetDefinitionType;
  /** URL of the image. e.g. https://example.com/image.png */
  url: string;
  /** URL of the image in dark mode. e.g. https://example.com/image-dark-mode.png */
  url_dark_theme?: string;
  sizing?: WidgetImageSizing;
  margin?: WidgetMargin;
  /** @default true */
  has_background: boolean;
  /** @default true */
  has_border: boolean;
  horizontal_align?: WidgetHorizontalAlign;
  vertical_align?: WidgetVerticalAlign;
}
// --- ImageWidgetDefinitionType ---
type ImageWidgetDefinitionType = "image";
// --- WidgetImageSizing ---
/** How to size the image on the widget. The values are based on the image `object-fit` CSS properties. **Note**: `zoom`, `fit` and `center` values are deprecated. */
type WidgetImageSizing = "fill" | "contain" | "cover" | "none" | "scale-down" | "zoom" | "fit" | "center";
// --- WidgetMargin ---
/** Size of the margins around the image. **Note**: `small` and `large` values are deprecated. */
type WidgetMargin = "sm" | "md" | "lg" | "small" | "large";
// --- WidgetHorizontalAlign ---
type WidgetHorizontalAlign = "center" | "left" | "right";
// --- IFrameWidgetDefinition ---
interface IFrameWidgetDefinition {
  type: IFrameWidgetDefinitionType;
  url: string;
}
// --- IFrameWidgetDefinitionType ---
type IFrameWidgetDefinitionType = "iframe";
// --- EventStreamWidgetDefinition ---
/** Only available on FREE layout dashboards. */
interface EventStreamWidgetDefinition {
  type: EventStreamWidgetDefinitionType;
  /** Query to filter the event stream with. */
  query: string;
  event_size?: WidgetEventSize;
  title?: string;
  title_size?: string;
  title_align?: WidgetTextAlign;
  description?: string;
  time?: WidgetTime;
  /** The execution method for multi-value filters. Can be either and or or. */
  tags_execution?: string;
}
// --- EventStreamWidgetDefinitionType ---
type EventStreamWidgetDefinitionType = "event_stream";
// --- EventTimelineWidgetDefinition ---
/** Only available on FREE layout dashboards. */
interface EventTimelineWidgetDefinition {
  type: EventTimelineWidgetDefinitionType;
  /** Query to filter the event timeline with. */
  query: string;
  title?: string;
  title_size?: string;
  title_align?: WidgetTextAlign;
  description?: string;
  time?: WidgetTime;
  /** The execution method for multi-value filters. Can be either and or or. */
  tags_execution?: string;
}
// --- EventTimelineWidgetDefinitionType ---
type EventTimelineWidgetDefinitionType = "event_timeline";
// --- LogStreamWidgetDefinition ---
interface LogStreamWidgetDefinition {
  type: LogStreamWidgetDefinitionType;
  /** An array of index names to query in the stream. Use [] to query all indexes at once. */
  indexes?: string[];
  /** Query to filter the log stream with. */
  query?: string;
  /** Which columns to display on the widget. */
  columns?: string[];
  show_date_column?: boolean;
  show_message_column?: boolean;
  message_display?: WidgetMessageDisplay;
  sort?: WidgetFieldSort;
  title?: string;
  title_size?: string;
  title_align?: WidgetTextAlign;
  description?: string;
  time?: WidgetTime;
}
// --- LogStreamWidgetDefinitionType ---
type LogStreamWidgetDefinitionType = "log_stream";
// --- WidgetMessageDisplay ---
/** Amount of log lines to display */
type WidgetMessageDisplay = "inline" | "expanded-md" | "expanded-lg";
// --- PowerpackWidgetDefinition ---
interface PowerpackWidgetDefinition {
  type: PowerpackWidgetDefinitionType;
  title?: string;
  /** Background color of the powerpack title. */
  background_color?: string;
  /** URL of image to display as a banner for the powerpack. */
  banner_img?: string;
  /** UUID of the associated powerpack. e.g. df43cf2a-6475-490d-b686-6fbc6cb9a49c */
  powerpack_id: string;
  template_variables?: PowerpackTemplateVariables;
  /** @default true */
  show_title: boolean;
}
// --- PowerpackWidgetDefinitionType ---
type PowerpackWidgetDefinitionType = "powerpack";
// --- PowerpackTemplateVariables ---
interface PowerpackTemplateVariables {
  /** Template variables controlled by the external resource, such as the dashboard this powerpack is on. */
  controlled_externally?: PowerpackTemplateVariableContents[];
  /** Template variables controlled at the powerpack level. */
  controlled_by_powerpack?: PowerpackTemplateVariableContents[];
}
// --- PowerpackTemplateVariableContents ---
interface PowerpackTemplateVariableContents {
  name: string;
  /** One or many template variable values, unioned together using `OR` if more than one is specified. */
  values: string[];
  /** The tag prefix associated with the variable. */
  prefix?: string;
}
// --- GroupWidgetDefinition ---
interface GroupWidgetDefinition {
  type: GroupWidgetDefinitionType;
  layout_type: WidgetLayoutType;
  widgets: {
  [key: string]: unknown;
  }[];
  title?: string;
  title_align?: WidgetTextAlign;
  background_color?: WidgetBackgroundColor;
  /** URL of image to display as a banner for the group. */
  banner_img?: string;
  /** @default true */
  show_title: boolean;
}
// --- GroupWidgetDefinitionType ---
type GroupWidgetDefinitionType = "group";
// --- WidgetLayoutType ---
type WidgetLayoutType = "ordered";
// --- LocalDatasetRequest ---
/** Notebook-only: In notebook context, visualization widget requests may include
 * LocalDatasetRequest items alongside standard request types. */
interface LocalDatasetRequest {
  request_type: "local_dataset";
  query: StructuredAnalysisQuery | SampledAnalysisQuery;
  response_format: "tabular" | "timeseries";
}
// --- TreeLocalDatasetRequest ---
interface TreeLocalDatasetRequest {
  request_type: "local_dataset";
  query: StructuredAnalysisQuery | SampledAnalysisQuery;
  response_format: "tabular" | "timeseries";
  projection?: { type: "toplist" | "sunburst" | "treemap" | "bar_chart"; dimensions: ({ column: string; dimension: "group" | "value" })[] };
}
// --- TimeseriesLocalDatasetRequest ---
interface TimeseriesLocalDatasetRequest {
  request_type: "local_dataset";
  query: StructuredAnalysisQuery | SampledAnalysisQuery;
  response_format: "tabular" | "timeseries";
  projection?: { type: "timeseries"; dimensions: ({ column: string; dimension: "time" | "group" | "value" })[] };
}
// --- StructuredAnalysisQuery ---
interface StructuredAnalysisQuery {
  type: "structured_analysis";
  source_dataset: string;
  transformations: ({ type: "filter"; filter?: string } | { type: "aggregation"; group_by?: { column: string; name?: string; interval?: string }[]; compute?: { column?: string; name?: string; aggregation: string }[]; sort?: { column: string; order: "asc" | "desc" }; limit?: number; time_aggregation?: { time_column: string; interval?: number } } | { type: "join"; join_type: string; target_dataset?: string; target_columns?: string[]; join_conditions?: { source_column: string; target_column: string }[] } | { type: "limit"; limit: number } | { type: "calculated_field"; name?: string; expression?: string } | { type: "cast_column_type"; source_column: string; target_type: "string" | "int64" | "float64" | "timestamp"; target_column: string } | { type: "grok"; source_column?: string; grok_expression?: string; keep_nulls?: boolean } | { type: "projection"; columns: { column: string; alias?: string }[] } | { type?: "sort"; column: string; order: "asc" | "desc" })[];
}
// --- SampledAnalysisQuery ---
interface SampledAnalysisQuery {
  type: "sampled_analysis";
  source_dataset: string;
  query_filter?: string;
  sample: { limit?: number };
}
// --- StructuredAnalysisTransformations ---
type StructuredAnalysisTransformations = { type: "filter"; filter?: string } | { type: "aggregation"; group_by?: { column: string; name?: string; interval?: string }[]; compute?: { column?: string; name?: string; aggregation: string }[]; sort?: { column: string; order: "asc" | "desc" }; limit?: number; time_aggregation?: { time_column: string; interval?: number } } | { type: "join"; join_type: string; target_dataset?: string; target_columns?: string[]; join_conditions?: { source_column: string; target_column: string }[] } | { type: "limit"; limit: number } | { type: "calculated_field"; name?: string; expression?: string } | { type: "cast_column_type"; source_column: string; target_type: "string" | "int64" | "float64" | "timestamp"; target_column: string } | { type: "grok"; source_column?: string; grok_expression?: string; keep_nulls?: boolean } | { type: "projection"; columns: { column: string; alias?: string }[] } | { type?: "sort"; column: string; order: "asc" | "desc" }[];
// --- AnalysisDataSourceDefinition ---
interface AnalysisDataSourceDefinition {
  type: "analysis_data_source";
  query: EventPlatformDataset | FormulaDataset | ReferentialDataset | PublishedAnalysisDataset | AnalysisDataset | SnowflakeQueryDataset;
}
// --- EventPlatformDataset ---
interface EventPlatformDataset {
  data_source: "audit" | "ci_pipelines" | "ci_tests" | "database_queries" | "errors" | "events" | "llm_observability" | "logs" | "monitors" | "monitor_groups" | "network" | "network_device_flows" | "product_analytics" | "rum" | "security_signals" | "spans" | "synthetics_test_runs";
  name: string;
  columns: ({ column: string; type: "string" | "int64" | "float64" | "bool" | "timestamp" | "array<string>" | "array<int64>" | "array<float64>" | "array<bool>" | "array<timestamp>"; alias?: string })[];
  time_window?: { from: number; to: number };
  search?: { query?: string };
  indexes?: string[];
  storage?: "live" | "hot" | "habanero" | "online_archives" | "driveline" | "flex_tier" | "case_insensitive" | "cloud_prem";
}
// --- ReferentialDataset ---
interface ReferentialDataset {
  data_source: "reference_table" | "managed_resource";
  name: string;
  table_name: string;
  query_filter?: string;
}
// --- FormulaDataset ---
interface FormulaDataset {
  data_source: "formula";
  name: string;
  response_format: "scalar" | "timeseries";
  time_window?: { from: number; to: number };
  queries: ({ data_source: "metrics"; name: string; query: string; aggregator?: null | "avg" | "min" | "max" | "sum" | "last" | "mean" | "area" | "l2norm" | "percentile" | "stddev" | "count_unique" })[];
  formulas: { formula: string; alias?: string }[];
}
// --- PublishedAnalysisDataset ---
interface PublishedAnalysisDataset {
  data_source: "published_analysis";
  name: string;
  dataset_id: string;
  columns?: ({ column: string; type: "string" | "int64" | "float64" | "bool" | "timestamp" | "json" | "hstore" | "interval" | "array<string>" | "array<int64>" | "array<float64>" | "array<bool>" | "array<timestamp>" | "array<json>" | "array<interval>"; alias?: string })[];
  time_window?: { from: number; to: number };
  query_filter?: string;
  provider?: "ddsql_query" | "notebook_cell";
}
// --- AnalysisDataset ---
interface AnalysisDataset {
  data_source: "analysis_dataset";
  name: string;
  query: { type: "sql_analysis"; sql_query: string } | { type: "structured_analysis"; source_dataset: string; transformations: ({ type: "filter"; filter?: string } | { type: "aggregation"; group_by?: { column: string; name?: string; interval?: string }[]; compute?: { column?: string; name?: string; aggregation: string }[]; sort?: { column: string; order: "asc" | "desc" }; limit?: number; time_aggregation?: { time_column: string; interval?: number } } | { type: "join"; join_type: string; target_dataset?: string; target_columns?: string[]; join_conditions?: { source_column: string; target_column: string }[] } | { type: "limit"; limit: number } | { type: "calculated_field"; name?: string; expression?: string } | { type: "cast_column_type"; source_column: string; target_type: "string" | "int64" | "float64" | "timestamp"; target_column: string } | { type: "grok"; source_column?: string; grok_expression?: string; keep_nulls?: boolean } | { type: "projection"; columns: { column: string; alias?: string }[] } | { type?: "sort"; column: string; order: "asc" | "desc" })[] } | { type: "sampled_analysis"; source_dataset: string; query_filter?: string; sample: { limit?: number } };
}
// --- SnowflakeQueryDataset ---
interface SnowflakeQueryDataset {
  data_source: "snowflake_query";
  name: string;
  sql_query: string;
}
// --- AnalysisSqlDefinition ---
interface AnalysisSqlDefinition {
  type: "analysis_sql";
  query: { data_source: "analysis_dataset"; name: string; query: { type: "sql_analysis"; sql_query: string } };
}
// --- AnalysisTransformationDefinition ---
interface AnalysisTransformationDefinition {
  type: "analysis_transformation";
  query: { data_source: "analysis_dataset"; name: string; query: { type: "structured_analysis"; source_dataset: string; transformations: ({ type: "filter"; filter?: string } | { type: "aggregation"; group_by?: { column: string; name?: string; interval?: string }[]; compute?: { column?: string; name?: string; aggregation: string }[]; sort?: { column: string; order: "asc" | "desc" }; limit?: number; time_aggregation?: { time_column: string; interval?: number } } | { type: "join"; join_type: string; target_dataset?: string; target_columns?: string[]; join_conditions?: { source_column: string; target_column: string }[] } | { type: "limit"; limit: number } | { type: "calculated_field"; name?: string; expression?: string } | { type: "cast_column_type"; source_column: string; target_type: "string" | "int64" | "float64" | "timestamp"; target_column: string } | { type: "grok"; source_column?: string; grok_expression?: string; keep_nulls?: boolean } | { type: "projection"; columns: { column: string; alias?: string }[] } | { type?: "sort"; column: string; order: "asc" | "desc" })[] } };
}
// --- MetricHostmapRequests ---
/** Metric-based host map request using direct fill/size queries. */
interface MetricHostmapRequests {
  fill?: HostMapRequest;
  size?: HostMapRequest;
}
